### ISSUE TITLE
Scrollbar can appear briefly above overlay panel

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#120]
I believe this only happens on macOS with autohiding scrollbars.

<img width="1440" alt="screen shot 2017-04-07 at 8 50 14 pm" src="https://cloud.githubusercontent.com/assets/1167259/24862540/015a94c0-1dcb-11e7-9c08-14cc5527fdec.png">

cc @rhamilto

**Comment by rhamilto** [comment]
> I believe this only happens on macOS with autohiding scrollbars.

Confirmed
