### ISSUE TITLE
npm run start reload loop

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#14]
I ran the instructions in the README.md file, was able to serve up the catalog, but in an infinite reload loop.  I suspect this is easy to resolve, will do some tinkering.  Meanwhile if anyone knows off the top of their head, let me know here.  I'll PR the README.md with a note on this.

![2017-03-15 10 57 30](https://cloud.githubusercontent.com/assets/280512/23954713/66ba949e-096e-11e7-9cd4-8cd362602154.gif)

@jeff-phillips-18 @dtaylor113 @spadgett

**Comment by dtaylor113** [comment]
Hi @benjaminapetersen , what does your additionalServers look like in config.js or config.local.js?
Thanks,
Dave

**Comment by dtaylor113** [comment]
Also, there seems to be an error in the URL of the screenshot above, something about "Unable to load details about the server" so I think your catalog app. is having issues connectiing to 'oc cluster up" perhaps?

**Comment by dtaylor113** [comment]
What should happen is when you first launch the catalog app. it should show you the log in screen.  I had to change all the 'localhost' in my config.local.js to my actual local IP address.

**Comment by dtaylor113** [comment]
Hi, just put up PR #15 , which should eliminate the reloads.  -thanks!

**Comment by spadgett** [comment]
We should add guards to avoid loops like this on a bad config

**Comment by benjaminapetersen** [comment]
FWIW, i just ran via the instructions in the README.md file.  I'm guessing that this actually will not work as I haven't installed anything specifically for catalog in my Vagrant VM... do we have instructions anywhere for that kind of setup?

**Comment by dtaylor113** [comment]
Hi, @jeff-phillips-18, is going through that now based on some instructions I wrote:

https://docs.google.com/document/d/1zsf_7j9jwd4mHLz0owY-I1DxHiBs9p1YwRf1rqZ9luQ/edit#heading=h.96kvdfx9vdvx

Also, PR #17 needs to be merged before real service classes show up in catalog.  

Thanks,
- Dave

**Comment by benjaminapetersen** [comment]
@dtaylor113 cool, looks like that google doc is locked down.
