### ISSUE TITLE
Edges of SaaS hover styles not clickable

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#140]
There is a dead area (in purple below) that's highlighted, but can't be clicked in the SaaS list.

![screen shot 2017-04-11 at 10 42 38 am](https://cloud.githubusercontent.com/assets/1167259/24918348/126ee4c6-1eae-11e7-83c0-3a42569a1a2f.png)

cc @cshinn @rhamilto

**Comment by rhamilto** [comment]
This is an easy fix.  [Line 26](https://github.com/openshift/origin-web-catalog/blob/master/src/styles/saas-list.less#L26) needs to move to [line 52](https://github.com/openshift/origin-web-catalog/blob/master/src/styles/saas-list.less#L52).  I'd do it, but I'm still having build issues.  :(

**Comment by spadgett** [comment]
Fixed by #141
