### ISSUE TITLE
[WIP] When Ordering Panel launched from Recently Viewed items is behind Search and Nav Bars

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#145]
Ordering Panel when launched from Recently Viewed on Project Summary/Landing Page Side Bar  appears behind the Search and Nav bars even though z-index's seem to be correct:

![image](https://cloud.githubusercontent.com/assets/12733153/24965537/4e685b3c-1f72-11e7-986e-2b383bdc5642.png)

Ordering Panel when launched from service catalog view appears on top of all items:
![image](https://cloud.githubusercontent.com/assets/12733153/24965642/a590028e-1f72-11e7-9983-9149d3f4aea7.png)

**Comment by dtaylor113** [comment]
@rhamilto , @spadgett , @cshinn   Scratching my head at this one, z-index's seem to be correct.  I think it's an issue because we have `<ordering-panel>` inside of `<landing-side-bar>` but I'm not sure what the root cause is.

**Comment by dtaylor113** [comment]
Code at https://github.com/dtaylor113/origin-web-catalog/tree/recently-viewed

**Comment by spadgett** [comment]
@dtaylor113 It's using the z-index from the sidebar here:

https://github.com/spadgett/origin-web-catalog/blob/f2ee4419289361c775ed630f4be887f626ac2ec9/src/styles/landing-page.less#L112

But you have to be careful changing that since it will cause the navbar dropdowns to open under the sidebar.

**Comment by dtaylor113** [comment]
@spadgett , ok, think you are correct even thought the z-index for `.catalogs-overlay-panel-wrapper` isn't showing up as overridden (striked-out formatting) in dev tools inspection.  Does the ancestor's z-index override children?  I tried '!important' in `.catalogs-overlay-panel-wrapper`, no luck.  Only thing that works is changing landing-side-bar's z-index to 1030 but that will appear behind dropdowns though

**Comment by spadgett** [comment]
It's because the sidebar is position fixed. You either need to move the overlay outside of the `.landing-search-area` element or set the z-index and positioning on a child of `.landing-search-area`. Not sure what's best, although I don't really like that we have 3 overlay dialogs now. I'd rather have one for the app.

cc @rhamilto @jeff-phillips-18

**Comment by dtaylor113** [comment]
> I don't really like that we have 3 overlay dialogs now. I'd rather have one for the app.

I think to fix this we do need to move `overlay-panel` outside of `<landing-side-bar>` and have search, catalog-service-view, and recently-viewed trigger openning/closing panel via `$rootscope.$emit` or component `&` bindings.

**Comment by spadgett** [comment]
That sounds reasonable to me.

**Comment by spadgett** [comment]
We'd probably want to use `$scope.$emit` here to send messages up the chain, but I think `&` bindings are better

**Comment by jeff-phillips-18** [comment]
We should make the overlay panel a service much like angular bootstrap uibModal

**Comment by dtaylor113** [comment]
fixed this via `$scope.$emit` and moving `<ordering-panel>` to parent landing page component.
