### ISSUE TITLE
No error displayed when delete project fails

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#162]
There's no indication in the UI that the delete project action failed.

![screen shot 2017-04-18 at 12 43 52 pm](https://cloud.githubusercontent.com/assets/1167259/25142409/c5265186-2434-11e7-8df4-c27202555c7f.png)

cc @jwforres

**Comment by spadgett** [comment]
Same problem for edit project

**Comment by spadgett** [comment]
@jeff-phillips-18 I think this is fixed?

**Comment by jeff-phillips-18** [comment]
@spadgett Yeah, fixed by #1471
