### ISSUE TITLE
Project Summary: Recently Viewed Items - Update After Ordering Panel closes

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#168]
Currently the Recently Viewed items gets updated immediately when one clicks on an item in Search, Service View, or from Project Summary side panel.  This causes the Recently Viewed items to shift before/during the opening of the Ordering Panel, which is distracting.
Request to change updating of the Recently Viewed items to after the Ordering Panel Closes.

**Comment by spadgett** [comment]
Fixed by #169
