### ISSUE TITLE
Overlay panel parameters

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#177]
@serenamarie125 @jwforres @rhamilto @ncameronbritt 

I'm looking for input on service / template parameters.  This is a pretty typical template, and many templates have over 40 parameters. I'm concerned the two-panel dialog doesn't scale well for more complicated forms. Any ideas on how to improve the experience?

Help below each field:

![template-fields-inline-help](https://cloud.githubusercontent.com/assets/1167259/25443758/cef3dd12-2a76-11e7-9c81-71048e347276.gif)

Help tooltips:

![template-fields-info-icons](https://cloud.githubusercontent.com/assets/1167259/25444139/1e32b0fa-2a78-11e7-9c9b-bf83588ad367.gif)

**Comment by dtaylor113** [comment]
Can they be separated into Required .vs Advanced Settings?  The latter we can hide in a dropdown

**Comment by beanh66** [comment]
@spadgett Was there any thought on having the left content static? It seems like a waste of space to have nothing displayed as the user scrolls.

**Comment by spadgett** [comment]
@beanh66 We can do that, although we'd need a separate scrollbar for the description if it's too long

**Comment by beanh66** [comment]
@spadgett Could we have a max number of characters we allow? I'm worried double scroll may look odd.

**Comment by ncameronbritt** [comment]
Being able to chunk up the form into proper wizard steps would be good too. I think that's been mentioned as a future goal. 

For now, is there a way to do it that where, if the user is going to accept the defaults ("simple" version), we only show the fields they would need to fill out? And if a user needs more advanced control, they could get to a full-page version of this form? Would the user who did a simple version then be able to go back and edit parameters?

**Comment by spadgett** [comment]
Here's how it looks with this template if we only show required parameters. @jwforres had concerns hiding required parameters with default values.

![screencast 2017-04-26 15-03-34](https://cloud.githubusercontent.com/assets/1167259/25451873/a2255b24-2a91-11e7-8caf-eb230899de82.gif)

**Comment by spadgett** [comment]
> Would the user who did a simple version then be able to go back and edit parameters?

No, and that's the concern. Some of the parameters might be difficult to change later.

**Comment by serenamarie125** [comment]
The original intent was that the left side would not scroll, unfortunately I wasn't straight forward in the documentation about that, sorry!  

My opinion is to use Field Level Help for help text.  In the walkthroughs that I have had with customers, there is a clear preference for cleaner UIs with the field level help.  Can we make this change now?

That being said, Is it possible for us to support both field level help & hints below?  Because there are some items like "try sample git repo" which I would imagine make more sense as a hint.

@spadgett another alternative is to add an additional step with the information ( i assumed this is something we will have to do regardless if we ever let people get to view catalog items without being logged in).  We *could* allow the project selection on this page as well, which would minimize the number of potential steps when offering parameters ( especially if they pick new ).  If we do this, we will have to figure a way to include the catalog item name in the stationary portion of the panel which shows the steps.

I'm a bit confused as to why we would fix this portion right now, if we are planning on asking customers at RH Summit about the number of parameters associated with templates, and if we can consolidate.  Maybe we can re-evaluate after i get that information?

**Comment by jwforres** [comment]
On Thu, Apr 27, 2017 at 8:46 AM, Serena Doyle <notifications@github.com>
wrote:

> The original intent was that the left side would not scroll, unfortunately
> I wasn't straight forward in the documentation about that, sorry!
>
> My opinion is to use Field Level Help for help text. In the walkthroughs
> that I have had with customers, there is a clear preference for cleaner UIs
> with the field level help. Can we make this change now?
>
> That being said, Is it possible for us to support both field level help &
> hints below? Because there are some items like "try sample git repo" which
> I would imagine make more sense as a hint.
>
For builder images yes we could do some as field level and some as hints.
Templates are basically like services you provision (and will be done that
way very soon).  In that case there is just a description coming from the
backend, we wouldn't know whether to show it as one way vs another, we just
have to pick one across the board.

> @spadgett <https://github.com/spadgett> another alternative is to add an
> additional step with the information ( i assumed this is something we will
> have to do regardless if we ever let people get to view catalog items
> without being logged in). We *could* allow the project selection on this
> page as well, which would minimize the number of potential steps when
> offering parameters ( especially if they pick new ). If we do this, we will
> have to figure a way to include the catalog item name in the stationary
> portion of the panel which shows the steps.
>
> I'm a bit confused as to why we would fix this portion right now, if we
> are planning on asking customers at RH Summit about the number of
> parameters associated with templates, and if we can consolidate. Maybe we
> can re-evaluate after i get that information?
>
We were asking for feedback on the builder image workflow that we have much
more control over.  Templates are basically out of our control, much like
services, people can choose to put whatever / however many parameters they
want in there and we have to be able to handle that.

**Comment by spadgett** [comment]
> I'm a bit confused as to why we would fix this portion right now, if we are planning on asking customers at RH Summit about the number of parameters associated with templates, and if we can consolidate. Maybe we can re-evaluate after i get that information?

To echo what Jessica said, we have no control over what parameters are defined. The parameters, labels, and any field-level help come from the template, and we have no hints on how they might be grouped or what is important. We only know if they're required or if they have default values.

**Comment by jwforres** [comment]
So we had a discussion about this, at this point I think we are proposing
what Cameron suggested.  We will hide all non-required fields, we will hide
all required and defaulted fields, and we will hide all required and
generated fields (generated will get a value generated for them
automatically if the user leaves them blank).   So basically from this
overlay context, what the user will see are only fields that absolutely
require their attention in order for the template to be provisioned.  The
"advanced" option would take them to a full-page form, and maintain any
data they had already filled out, just like @spadgett did for builder
images.

As far as the field level help, I only want to make that change in this
overlay concept for now.  All of our full page forms across the console use
help-block text today, switching all of them right now is a big effort.
I'd prefer to test the field level help in the "new" experience (overlays
only) for 3.6

@serenamarie125 thoughts?

**Comment by serenamarie125** [comment]
@jwforres I'm good with this approach for now.

**Comment by spadgett** [comment]
I opened a separate issue (#196) for keeping the description from scrolling.
