### ISSUE TITLE
White block visible at bottom of page when loading

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#179]
![screen shot 2017-04-27 at 8 04 10 am](https://cloud.githubusercontent.com/assets/1167259/25483245/10665a52-2b23-11e7-8c98-292150d4caa1.png)

cc @rhamilto @cshinn

**Comment by cshinn** [comment]
Given that there aren't really any grey elements anymore, should we just make the .spinner-panel background white?

**Comment by serenamarie125** [comment]
@cshinn can you take this issue? After talking to @jeff-phillips-18 we were thinking:
- set the bg image on the entire landing area not just the main
- set the margins so there is some aroudn the catalog browsing area
- set the bg of the catalogs area to white

**Comment by cshinn** [comment]
@serenamarie125 is this what you had in mind?
![screen shot 2017-04-27 at 10 15 21 am](https://cloud.githubusercontent.com/assets/3300756/25487530/8014e7ec-2b32-11e7-9d20-2f7fcf78cc96.png)

**Comment by jeff-phillips-18** [comment]
@cshinn 👍

**Comment by cshinn** [comment]
re: the issue, this means that the loading state would just be a big grey rectangle floating in the middle of the background image. Is that acceptable to everyone? I think the padding sort of makes it seem like it's not rooted, insubstantial

**Comment by spadgett** [comment]
> this means that the loading state would just be a big grey rectangle floating in the middle of the background image.

For context, all of the other pages in the web console show the message "Loading..." instead of using a spinner. (I mention it since we've recently had other discussions about consistency.)

**Comment by jeff-phillips-18** [comment]
@cshinn couldn't that background be changed to white?

@spadgett agreed, it should be consistent when loading.

It should also handle the case where there are no services available and show the standard empty page content.

**Comment by serenamarie125** [comment]
@cshinn I like what you've got so far.
I agree with @spadgett that we need consistency.  Sam can you either embed a screenshot of one of the areas already doing this, or point to the code so we get consistency?
@jeff-phillips-18 brings up a good point, we should have an empty state,

**Comment by spadgett** [comment]
@serenamarie125 Sorry, forgot to follow up on this!

Usually it's just the text "Loading..." in normal font:

<img width="809" alt="screen shot 2017-05-02 at 12 14 06 pm" src="https://cloud.githubusercontent.com/assets/1167259/25627594/19a276ca-2f31-11e7-873c-727319e46b41.png">

Although during API discovery when you first load the console, we use this style:

<img width="644" alt="screen shot 2017-05-02 at 12 14 40 pm" src="https://cloud.githubusercontent.com/assets/1167259/25627610/29eb444e-2f31-11e7-9a42-f5b913070b6b.png">

There are a few places when something might take a long time to load (like logs) where we use an animated ellipsis.

**Comment by cshinn** [comment]
This discussion seems to revolve around the same issue as #198

**Comment by jwforres** [comment]
Its related but slightly different since its related to the loading state before we know what categories to show
