### ISSUE TITLE
Two scrollbars visible when catalog content too long for the page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#182]
@serenamarie125 @beanh66 @cshinn  @jwforres Wanted to get your opinion on this. The double scrollbars feel awkward to me.

![screen shot 2017-04-27 at 1 29 41 pm](https://cloud.githubusercontent.com/assets/1167259/25496123/d0c0b962-2b4d-11e7-9cf6-e22c9747ea25.png)

**Comment by beanh66** [comment]
@spadgett Agreed it feels awkward and seems hard to use. I am wondering if the whole page should scroll to see more catalog items, rather than just the subcategory section. What are your thoughts?

**Comment by spadgett** [comment]
We put a max height on the subcategory section in case a tab wrapped below so it would be visible, although I think in many cases it will still be off the page. It was mostly a problem when we were showing the subcategories still for "All," and I know we're working a different design for mobile.

>  I am wondering if the whole page should scroll to see more catalog items, rather than just the subcategory section. What are your thoughts?

I agree.

**Comment by beanh66** [comment]
@spadgett I remember the conversations around the tabs and why we thought scrolling within a subcategory would make sense, but after interacting with it, I don't know that the separate scroll bar solves that problem and it may create another issue with usability. I am getting feedback on the tabbed structure at summit, including how they wrap and scroll 👍

**Comment by serenamarie125** [comment]
@spadgett I think we should remove the inner scroll.  I think scrolling in general has changed since our initial design.  I agree that the inner scroll is an issue.

That being said, it would be great if we could restyle the outer scroll so it blends in a bit more - maybe if the background was closer in color to our project panel background or something.

**Comment by spadgett** [comment]
Thanks @serenamarie125 and @beanh66 

@rhamilto volunteered to look at this, including restyling the scrollbar

**Comment by serenamarie125** [comment]
Excellent, thanks @rhamilto @spadgett
