### ISSUE TITLE
SaaS offerings should not be using a click handler to open the URL

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#185]
We are only planning to support opening a URL right now, we should not be using click handlers for that, we should be using appropriate links with hrefs so that right-click -> open in new tab behaviors are not broken.

**Comment by jwforres** [comment]
cc @dtaylor113 

I think @rhamilto is currently in the process of changing the markup on these, so it may be easy for him to make this change while he is in that template.

**Comment by dtaylor113** [comment]
@jwforres , @rhamilto , ok, easy enough fix.   @rhamilto let me know if you can do this or if you'd like me to do it.  -thanks

**Comment by rhamilto** [comment]
@dtaylor113, I'm about to open a PR with the change...

**Comment by rhamilto** [comment]
Nevermind.  I'll wait for your PR to merge.

**Comment by dtaylor113** [comment]
Sorry @rhamilto, I had some free cycles; hope I didn't step on your toes :-)
