### ISSUE TITLE
We should truncate long service title names

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#189]
![screen shot 2017-04-28 at 12 31 02 pm](https://cloud.githubusercontent.com/assets/1167259/25537964/b88dfbcc-2c0e-11e7-8a83-1c31ff56a90b.png)

![screen shot 2017-04-28 at 12 33 55 pm](https://cloud.githubusercontent.com/assets/1167259/25538032/ffdcbf9a-2c0e-11e7-82c4-90bb1571a8a3.png)

cc @rhamilto @sg00dwin @serenamarie125 @jeff-phillips-18

**Comment by serenamarie125** [comment]
can't imagine it looks good while browsing or viewing a search result either :( 
@spadgett what is the max length of the service name ?  Please tell me there is one ...

**Comment by spadgett** [comment]
@serenamarie125 I don't believe there's a max length for display name since in the Open Service Broker API it's not formalized. It's just a property on a JSON metadata object.

**Comment by spadgett** [comment]
It can overflow the search box, too (although hard to tell in this screenshot)

![screen shot 2017-04-28 at 12 41 45 pm](https://cloud.githubusercontent.com/assets/1167259/25538280/13b83e4e-2c10-11e7-9e1a-177f6ec8a934.png)

**Comment by spadgett** [comment]
Making this a general issue to cover all cases, not just the dialogs. @sg00dwin has already started looking at this for #170

**Comment by rhamilto** [comment]
Related follow on:  https://github.com/openshift/origin-web-catalog/issues/220
