### ISSUE TITLE
Description should not scroll with dialog content

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#196]
The description in the left panel should not scroll with the rest of the dialog content. See discussion in #177

**Comment by rhamilto** [comment]
Presumably this means the description content should scroll independently of the form content when necessary (e.g., height of description exceeds 300px)?

**Comment by spadgett** [comment]
Some debate over that. There was concern over having two scrollbars in #177. We might just truncate.

**Comment by spadgett** [comment]
Although it would be nice to make sure the documentation link is on screen if there is one.

**Comment by rhamilto** [comment]
![screen shot 2017-05-01 at 4 25 19 pm](https://cloud.githubusercontent.com/assets/895728/25593510/daf9efda-2e8a-11e7-86f6-a315d032fe6e.PNG)

Granted, this is an odd viewport size, but it is possible.

**Comment by spadgett** [comment]
@rhamilto Not ideal, but OK as long as the right panel scrolls?
