### ISSUE TITLE
Look of the OOTB empty SaaS offering section in IE11

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#198]
Are we happy with the way the empty SaaS offering section looks?  If we are shipping both origin / OCP with nothing in that section (which is the current plan) then this is what everyone will see when they install openshift OOTB.

![no-saas-services](https://cloud.githubusercontent.com/assets/1467629/25624532/a84618d2-2f27-11e7-9086-9b46eebcb717.png)

**Comment by jwforres** [comment]
cc @sspeiche @serenamarie125 @cshinn @spadgett @smarterclayton

**Comment by serenamarie125** [comment]
@cshinn had some changes to add a margin around the catalog which made it look better visually.  Chris did you put up a PR for that?

**Comment by jwforres** [comment]
ah right i remember that, it allowed some of the background to show through around the edges, that would probably help

**Comment by cshinn** [comment]
![screen shot 2017-04-27 at 10 15 21 am](https://cloud.githubusercontent.com/assets/3300756/25625637/06ee4118-2f2b-11e7-9dbb-0e4b141871d3.png)
![screen shot 2017-04-27 at 10 19 07 am](https://cloud.githubusercontent.com/assets/3300756/25625641/0bab9066-2f2b-11e7-88d8-2696b95e44d3.png)
![screen shot 2017-04-27 at 10 41 30 am](https://cloud.githubusercontent.com/assets/3300756/25625648/0e268ea4-2f2b-11e7-8f1b-3b5acd60ea30.png)

**Comment by cshinn** [comment]
I don't have a super strong opinion one way or the other on this. Might be worth checking with visuals.

**Comment by jwforres** [comment]
i think having the background image take up most of the screen like in your third screenshot is a bit much, can we have the white extend closer to the bottom and have a consistent margin going all the way around left/bottom/right?

**Comment by cshinn** [comment]
@jwforres something more like this?
![screen shot 2017-04-27 at 10 42 12 am](https://cloud.githubusercontent.com/assets/3300756/25626122/83170ada-2f2c-11e7-8341-032d98a7bc09.png)

**Comment by jwforres** [comment]
yeah, its a lot of white, im not sure which is better :-\

**Comment by serenamarie125** [comment]
@jwforres I just had someone ask if the background image is customizable.  It is, correct?
imo, I'd go with the background image.  As this becomes customizable, if we had the SaaS area under Browse Catalog, we would want it to take up as little space as needed.

**Comment by jwforres** [comment]
On Tue, May 2, 2017 at 3:10 PM, Serena Doyle <notifications@github.com>
wrote:

> @jwforres <https://github.com/jwforres> I just had someone ask if the
> background image is customizable. It is, correct?
>
It is because in theory all of our CSS can be overridden by extension CSS.

**Comment by jennyhaines** [comment]
@jwforres @cshinn -

I think there should be more space above and below those four selectable application types, and those four icons should be slightly smaller. Right now, they seem a little crowded.

Also, to help out in the case that there is just one catalog item or row of items shown (as in Chris's third screenshot), it might be nice to have a minimum of two rows-worth of white container space. This would help the ratio of background:white container.

**Comment by jennyhaines** [comment]
@jwforres @cshinn 

Here is what I mean by always having at least 2 rows of white container space (I know that these catalog items are not aligned with CI/CD, but this is just for visual illustration purposes):

![openshift-next-2rows](https://cloud.githubusercontent.com/assets/24898297/25807667/a17259a0-33d5-11e7-932c-3a3aa6611800.png)

![openshift-next-1row](https://cloud.githubusercontent.com/assets/24898297/25807676/a776a4fa-33d5-11e7-8cd3-b1358f44eb38.png)

(Basically, even if there is only one row of catalog items, there is at minimum two rows worth of container space. This helps to balance the space out when there are no selectable application types at the top.)

**Comment by beanh66** [comment]
@jennyhaines having the two rows of white looks great! One quick question, can we still have the blue borders on the right and left sides like @cshinn has?  If so, do you mind adding the side margins to your mock? Let us know what you think.

**Comment by serenamarie125** [comment]
+1 @beanh66 I think the look with the margins is nicer.

**Comment by jennyhaines** [comment]
@beanh66 @serenamarie125 @cshinn - Here it is with the margin included. I think this also looks nice!

![openshift-next-2rows](https://cloud.githubusercontent.com/assets/24898297/25857631/a9d90f12-34a7-11e7-8512-b891dd15861c.png)

**Comment by cshinn** [comment]
I think we may be on the road to Abilene here. Do we prefer the image at the bottom to the white background? @serenamarie125 @kybaker @jennyhaines @rhamilto @jwforres @beanh66

**Comment by rhamilto** [comment]
I'd like to see what the visual designers come up with given the new requirements.  I'm not sure any of the modifications to the existing design are successful.

**Comment by jennyhaines** [comment]
@cshinn @rhamilto - I think that the last of the options (with the minimum 2 rows or whitespace) is the most successful from a visual standpoint because the white does not completely overtake the page, nor does it look so small that the blue background overtakes everything.

**Comment by cshinn** [comment]
My personal inclination is towards the initial version, (white background) but I think the bordered version looks good as well. @rhamilto out of curiosity, which new requirements did you have in mind?

**Comment by beanh66** [comment]
@cshinn I think I like what @jennyhaines is suggesting the best.

**Comment by spadgett** [comment]
> I think we may be on the road to Abilene here. Do we prefer the image at the bottom to the white background?

For what it's worth, I prefer the current style (white background). The edge to edge white looks better to me when there's more content in the catalog, which hopefully is the normal case. We'll also be showing the templates, not just the builders, now that we've finished https://github.com/openshift/origin-web-console/pull/1492

**Comment by spadgett** [comment]
Is this considered done now that #261 merged?

**Comment by jwforres** [comment]
i think we still have an issue left in IE11 based on the comments in #261  i'll update the title and reduce to a p3

**Comment by jwforres** [comment]
will also remove from the 3.6 milestone, not urgent that we fix this

**Comment by rhamilto** [comment]
Reviving this discussion as the release of 3.7 is drawing near.  Here is an updated screenshot of origin:

![localhost-9000-dev-console-oauth](https://user-images.githubusercontent.com/895728/32175430-57703ac4-bd5b-11e7-9ee0-efe8261f8fff.png)

Note the background image may change with https://github.com/openshift/origin-web-catalog/pull/541

 Are we good with the way the way things look and can close this issue?

**Comment by spadgett** [comment]
@rhamilto Is that how it looks on IE11? I think the IE11 bug was the only remaining concern.

**Comment by rhamilto** [comment]
@rhamilto Is that how it looks on IE11? I think the IE11 bug was the only remaining concern.

Looks ok to me.

![screen shot 2017-10-30 at 11 06 05 am](https://user-images.githubusercontent.com/895728/32179026-a7e68928-bd64-11e7-9b87-3aa6671b4b8d.PNG)

**Comment by spadgett** [comment]
I think this is fixed then. Closing the issue. If anyone disagree, please comment or reopen.

Thanks @rhamilto
