### ISSUE TITLE
div.form-group.invisible creates empty space at bottom of create from builder form

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#204]
![screen shot 2017-05-03 at 9 15 08 am](https://cloud.githubusercontent.com/assets/895728/25662158/75188ee4-2fe1-11e7-94b0-658a2308b864.PNG)

@spadgett, based on your comment in the template, I'm guessing you determined this was the lesser of evils; however, it becomes a bit more obvious when only the right column scrolls (which I'm still working on).

**Comment by spadgett** [comment]
@rhamilto It prevents the dialog from resizing suddenly when the projects load, but yeah, not ideal. We want to make the link work always, then the problems goes away.

https://bugzilla.redhat.com/show_bug.cgi?id=1442978
