### ISSUE TITLE
Logo img with certain height/widths are distorted in Firefox

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-catalog#210]
Should switch to setting these as `background-image` and use `background-size` to control size.

Ex: PHP and AWS
<img width="306" alt="img-logos" src="https://cloud.githubusercontent.com/assets/1874151/25705297/ce6218a2-30aa-11e7-8da3-b9f7477ee504.png">

**Comment by spadgett** [comment]
Does Firefox not maintain the image aspect ratio when you set min-height/min-width?

**Comment by spadgett** [comment]
@rhamilto fyi

**Comment by rhamilto** [comment]
I'm not able to reproduce this in Firefox 53.0.2.  What am I missing?
![screen shot 2017-05-12 at 10 23 26 am](https://cloud.githubusercontent.com/assets/895728/26002251/11cd7462-36fd-11e7-8330-23c5c41e98af.PNG)

**Comment by rhamilto** [comment]
Ah!  I am able to reproduce in Firefox 45.9.0 ESR.  Do we care about supporting that version of Firefox?

**Comment by sg00dwin** [comment]
Yep I'm seeing it in Firefox 45.8.0 ESR.
Considering that it's "intended for groups who deploy and maintain the desktop environment in large organizations such as universities and other schools, county or city governments and businesses", I would think so.
https://www.mozilla.org/en-US/firefox/organizations/

**Comment by rhamilto** [comment]
But [45 ESR is going to be end-of-life'd around June 13 2017](https://www.mozilla.org/en-US/firefox/organizations/faq/).  Given that fact and that the new landing page is in tech preview, I don't think we should bother fixing the bug.
