### ISSUE TITLE
browse catalog tabs jump around at certain resolutions

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#212]
At about 1024px screen width my Python tab plays catch me if you can:

![screen shot 2017-05-05 at 9 40 45 am](https://cloud.githubusercontent.com/assets/280512/25747882/11814e1a-3177-11e7-8dd8-120e0b7e4e2c.png)
![screen shot 2017-05-05 at 9 40 50 am](https://cloud.githubusercontent.com/assets/280512/25747881/117fe30e-3177-11e7-9217-7fa7dedd3419.png)

@rhamilto @sg00dwin  @jeff-phillips-18 @dtaylor113

**Comment by serenamarie125** [comment]
This is the current design @benjaminapetersen .  if one of the subcategories in the first row is selected, the subsequent rows of subcategories will be shown below the shown services.

**Comment by beanh66** [comment]
We should improve this part of the design. I got some feedback at Summit regarding interaction with these tabs @serenamarie125

**Comment by benjaminapetersen** [comment]
Yeah, maybe if there was more than one item in the second row it would have felt intentional. With a lone tile jumping around it feels a little bit broken.  

Throwing out a suggestion, perhaps a subtle/transparent block around the orphan, matching it up to the first row?  Not sure if that fixes the jump though.

![catalog-tabs-orphan](https://cloud.githubusercontent.com/assets/280512/25750413/a1d295de-317f-11e7-879f-0579f1823486.png)
