### ISSUE TITLE
Indicate truncation of long service names with a visual indicator

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#220]
We either are or will be limiting service names to 3 lines of text [1]; however, we're providing no visual indicator that we're doing so.  We need to determine a cross-browser compatible solution and implement it.

[1] 
* Search results dropdown
* Browse
* Sidebar
* Panel overlay
   Note:  make sure $ctrl.serviceClass.resource.osbMetadata.documentationUrl is always visible! (move to top near name?)

**Comment by beanh66** [comment]
@rhamilto What do you think about showing an ellipses and then on hover, displaying the full name?

**Comment by rhamilto** [comment]
> @rhamilto What do you think about showing an ellipses and then on hover, displaying the full name?

That's an option, but remember that hover isn't available on mobile...

**Comment by beanh66** [comment]
Good point, I think we would be okay with cutting off the end of a service name on mobile though in this case @rhamilto

**Comment by rhamilto** [comment]
https://codepen.io/anon/pen/YVjrZY looks promising.  Gonna give it a whirl.

**Comment by rhamilto** [comment]
> https://codepen.io/anon/pen/YVjrZY looks promising. Gonna give it a whirl.

Drat.  Since the fallback solution for Firefox and IE/Edge always applies, this solution results in ellipses even if the content doesn't overflow.  :(
<img width="726" alt="screen shot 2017-05-16 at 1 45 18 pm" src="https://cloud.githubusercontent.com/assets/895728/26120215/fc16b3d8-3a3d-11e7-82e4-f901d885b982.PNG">
