### ISSUE TITLE
Overlay close button too close to wizard step text on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#232]
![openshift catalog components 2017-05-17 07-25-12](https://cloud.githubusercontent.com/assets/1167259/26151753/21a74a74-3ad2-11e7-9b89-7871ec41971f.png)

@jeff-phillips-18 I suspect when we add a fourth step for bind, they won't fit anymore on mobile.

**Comment by jeff-phillips-18** [comment]
I will make sure this is fixed while creating the bind steps.
