### ISSUE TITLE
Project list items on the landing page don't utilize tileClick directive

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#239]
Thus requiring clicking the project name directly rather than the entire project item row the way the full project list page does.  We should move the tileClick directive to origin-web-common so it can be used in both the catalog and the console.

**Comment by spadgett** [comment]
See https://github.com/openshift/origin-web-console/issues/1485#issuecomment-297999688 

cc @ncameronbritt

**Comment by rhamilto** [comment]
Fixed by #240
