### ISSUE TITLE
Can no longer click kebab in landing page project summary

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#245]
Looks like the kebab menu is a `button` instead of an `a`, and the `tile-click` directive only special cases clicks on the `a` element.

**Comment by spadgett** [comment]
The kebab navigates to the project rather than opening a menu.

**Comment by rhamilto** [comment]
Thanks for catching and fixing, @spadgett.  We're using an &lt;a&gt; for the kebab on the project list page.  Presumably we should be consistent?

**Comment by spadgett** [comment]
Button is probably more correct, although we use `<a>` in a whole bunch of places in the console :(

**Comment by jwforres** [comment]
If the a's have role=button its fine, if they don't then its technically an
accessibility bug.

**Comment by spadgett** [comment]
Or `aria-haspopup`

https://www.w3.org/TR/wai-aria/states_and_properties#aria-haspopup

`button` is nice because we can disable it unlike links, although in some places in a form it can break form submission using enter. I'm inclined to leave well enough alone, or revisit if needed when we look at accessibility
