### ISSUE TITLE
select-project component shouldn't show projects being deleted

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#268]
The select-project component shows all projects, even those being deleted. We should filter out those with a deletion timestamp which means they're scheduled for deletion.

**Comment by spadgett** [comment]
Now that we're doing foreground deletions, we're more likely to hit this.

**Comment by cdcabrera** [comment]
@spadgett are we aiming to ... ?
- either place this as a filter update in ```origin-web-common``` or within ```catalog```, possibly as a modification to an existing filter
- or simply filter it within the controller
