### ISSUE TITLE
Builder image create flow

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#27]
I wanted to start discussion on supported builder images in the catalog. These are the source-to-image language builders like Wildfly, Node.js, Ruby, etc., that we support today. I have some concerns, both technical and around the UX.

Note I'm talking specifically about the language builders and not services in the service catalog.

### It's a complex form

For context, here is the create form will all sections expanded. It's enormous. I've scaled down the image so you can see how tall the form is. For some fields, it pops up additional dialogs and file browsers.

![create-form](https://cloud.githubusercontent.com/assets/1167259/24164409/ff08e78a-0e43-11e7-920e-8c1a34245099.png)

I think this form is too complex as-if for the ordering panel. We have a card to break the form into a wizard in our backlog.

https://trello.com/c/wxH53dyz

### Many dependencies

The related problem is the number of services and Angular directives this form uses. The list below is not everything, but these are some of the larger services and directives it uses. (I have some notes with a more complete list. It's too large to include here.) These directives are reused for other editors, so changes to them will affect many places in the web console.

*I'd guess pulling all of these in will put close to half of the web console code into the common repo.* Pulling this much code into the common repository will make maintenance of origin-web-console difficult.

**Services**

ApplicationGenerator
LimitRangesService
MetricsService (no metrics HPA warning, could be factored out)
HPAService
QuotaService
SecretsService
ImagesService
ModalsService (used, but could be factored out)

**Editor Directives**

osc-secrets
create-secret
osc-routing
osc-file-input
key-value-editor
osc-autoscaling
edit-request-limit
label-editor

**Other Dependencies**

Ace Editor

### Proposal

I suggest we don't try to pull all of this into the catalog repo. The tiles can have a click handler registered with the catalog component. Then we can decouple the ordering panel from the catalog itself, and some of the actions can be handled by existing code in the origin-web-console repo when needed.

Normal service classes can use the ordering panel as in the current designs. For builders, we might have two forms:

1. A simple form that uses the ordering panel and prompts for a few fields (name, Git repository, and possibly source secrets for private Git repositories)
1. A more complex form -- like the current form -- that is linked out from the ordering panel.

Longer term we can look at improving the create form by making it multiple wizard steps or possibly removing less important items to keep it manageable.

When the catalog is used outside of origin-web-console, we can show the simple form with a link out to the web console for the more advanced create options.

@jwforres @jeff-phillips-18 @dtaylor113 @serenamarie125 @ncameronbritt @lizsurette

Thoughts?

**Comment by jwforres** [comment]
Agree with @spadgett that we can't pull in that much source from the web console into the other repos, that's just not maintainable.

I think accepting a click handler for the tiles is the right approach, it can be up to the click handler to decide what to do with the item that is sent to it.

**Comment by jeff-phillips-18** [comment]
The catalogs ordering panel could provide the simple case but allow transclusion for the complex forms. So, the click handler can still use the ordering panel either way (keeping the experience the same) but decide to use the simple form (from catalogs) or the complex form (from console).

**Comment by jwforres** [comment]
@spadgett is there anything else we want to address here, at least for now we've gone with the approach of going to a full form for the advanced workflow?  If we want to take a look at changing how we are handling this behavior in general across all the dialogs that would probably need to be a design / impl work for 3.7 timeframe.

**Comment by spadgett** [comment]
The thing I can think of is supporting the advanced options link when creating a project, but we have a Bugzilla for that.

Closing the issue.
