### ISSUE TITLE
Hide username param coming from template broker

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#291]
opening so we don't lose track of this

**Comment by jwforres** [comment]
fyi @bparees

**Comment by spadgett** [comment]
@jwforres @bparees @jim-minter 

Confirming my understanding so we're all on the same page :)

* Template broker will continue to send the `template.openshift.io/requester-username` in its parameter schema.
* UI will look for the requester username parameter and hide it in the form.
* UI will send the logged-in username in the provision request as the requester username parameter value.

**Comment by spadgett** [comment]
@pmorie FYI

**Comment by bparees** [comment]
@spadgett sounds right to me.
