### ISSUE TITLE
SAAS Offerings overflow in large screen mode when lots of them

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-catalog#296]
![image](https://user-images.githubusercontent.com/11633780/27142616-8cc2288c-50f9-11e7-9948-f3c0fc0634a8.png)

Also, I am able to tab to SAAS offerings that are hidden off screen (shown via Show More button) and this scrolls them into view.

**Comment by serenamarie125** [comment]
I thought there was a max of 4, and then we were showing "show more" ? http://openshift.github.io/openshift-origin-design/web-console/1-homepage/offerings
@beanh66 ?

**Comment by beanh66** [comment]
@serenamarie125 @jeff-phillips-18 Agreed, we should not show more than 4. Then when there are either more then 4 or there is a smaller screen resolution and a second row is needed, "Show More" should appear.
