### ISSUE TITLE
Minor Spacing & Sizing Tweaks

### ISSUE THREAD

**Issue by jennyhaines** [openshift/origin-web-catalog#299]
@jeff-phillips-18 @serenamarie125  Hi! Here are two things that shouldn't take very long, but will provide a lot of "bang for your buck" to make the screen look more elegant:

- The names of the catalog items (ex: “Node.js”) should be closer to their respective icons… moved up 10px closer.

- The four large icons in that top portion should be smaller… about 30% smaller. Making them smaller would create a bit more "breathing room" (aka whitespace) if the same panel height stays the same. They seem a little "in your face" at the current size.

This example of the spacing/sizing looks rough because I was editing a flat screenshot (hence the weird blue cutout boxes in the background that wouldn't really be there) Let me know if you have any questions... thanks!

![changes](https://user-images.githubusercontent.com/24898297/27151335-43c89a52-5118-11e7-9965-6af50b36911e.png)

**Comment by jeff-phillips-18** [comment]
@jennyhaines  For the service items, there is a blue circle on hover which may change your thoughts on some of the spacing there:

![image](https://user-images.githubusercontent.com/11633780/27151761-985edc7e-5119-11e7-8328-7632d4029ac8.png)

**Comment by jennyhaines** [comment]
aha... I see. In that case, I see this as a possible solution to tighten things up (because in my opinion, things are looking pretty loose with the current amount of space between the icons and the labels:
![changes2](https://user-images.githubusercontent.com/24898297/27154263-69abfa52-5122-11e7-8463-482f6424e074.png)

And here is the before and after in context... What do you think? @serenamarie125 @jeff-phillips-18 @jwforres :

### **Before:**
![before](https://user-images.githubusercontent.com/24898297/27154592-97d83a02-5123-11e7-9b9b-b4276d88cc06.png)


### **After:**
![after](https://user-images.githubusercontent.com/24898297/27154600-9cd099e6-5123-11e7-90e5-df9ac4edd20c.png)
