### ISSUE TITLE
Project select in ordering panel shouldn't show projects where I am only a viewer

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#318]
The select project dropdown when ordering anything should not show projects that you can't add to. 

We normally use AuthorizationService.canIAddToProject to check a particular project, but this would require a separate rules check against the server for every project that comes back in your project list.

An alternative would be to show the projects in the dropdown but do a rules check on it after its been selected and disable the Next button if you don't have the correct rights.  Not optimal user experience but possibly the best we can do from a performance perspective right now.

This was never an issue before because we were in the context of a project when adding and had already done the rules check.

**Comment by jwforres** [comment]
cc @spadgett

**Comment by dtaylor113** [comment]
@jwforres, so would it be a mix of projects one could and could not add to?  Or as a 'viewer', would I be blocked from adding to any/all projects?

**Comment by jwforres** [comment]
when we get the list of projects all we know is that you have AT LEAST view rights on that project, you may also have edit+ rights on that project, we can only do a detailed check on a per project basis.  So yes the list we get back is a mix of things you may or may not be able to actually add things to.

**Comment by jwforres** [comment]
Re-opening because we needed to rollback the original change, more details in https://github.com/openshift/origin-web-catalog/pull/340/files#diff-6fbc690320c27b7b184bcc1d67ec8cc0R70
