### ISSUE TITLE
Catalog showcase goes into redirect loop with invalid config

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#32]
It's very easy to get into a redirect loop if the catalog config is incorrect. We should improve our error handling.

**Comment by jeff-phillips-18** [comment]
One problem is that the additional servers are treated like the necessary servers. It is easy to not have the additionalServers setup correctly (since they may need to be created). Should we continue on if we fail  to connect to the additionalServers in the config?

@spadgett @jwforres

**Comment by spadgett** [comment]
@jeff-phillips-18 I think it's OK if it fails, but it shouldn't keep reloading the page again and again. If nothing else, it makes it difficult to troubleshoot the problem. I'm seeing what @benjaminapetersen saw in #14.

We should also change the default config.js. The additional servers [1] won't likely work for anyone. Maybe use mock data by default for now? There is some set up to show real service classes.

[1] https://github.com/openshift/origin-web-catalog/blob/master/app/config.js#L24-L27

**Comment by benjaminapetersen** [comment]
Yes, definitely.  Ideally fail once & give a good error message?  Looping is a pain, console gets cleared so there is no good way to trouble shoot (other than pester other people who might know the cause).

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen  Can you try this again with the latest commits? There have been a few changes that may have resolved this as I don't see the issue anymore.

**Comment by spadgett** [comment]
@jeff-phillips-18 I saw this yesterday morning and again this morning with a valid config. Both times stopping and restarting `npm run start` fixed it. I had to accept the localhost:9001 cert again as well, which might be related.

**Comment by jeff-phillips-18** [comment]
I see that issue (typically every morning) but it goes to the error page correctly without looping. Eventually it seems the service catalog server responds and it works (no npm restarting). Same issue in the console.

**Comment by dtaylor113** [comment]
This is the behavior I am seeing as well.  I haven't seen the looping since we added the error handling page/route.

**Comment by benjaminapetersen** [comment]
Haven't tried it again yet but will take a look.

**Comment by jwforres** [comment]
I still see this problem, at least from the main console, if the service catalog cert hasn't been accepted. I believe we had discussed handling errors on additionalServers loading differently than we handle the main API discovery.  Since additionalServers is supposed to always be for prototyping purposes.  But any change to that will be in common in the api discovery code.

**Comment by benjaminapetersen** [comment]
Yup. still kinda fiddly to get all setup.

**Comment by spadgett** [comment]
@jwforres You should be able to say `required: false` now in the additional servers stanza

**Comment by spadgett** [comment]
I believe this is no longer an issue now that we have the aggregator and don't need additional servers.
