### ISSUE TITLE
Unnecessary scrollbar when saas offerings are present

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#325]
When the saas offerings are present, the height of the main content area is set to a height larger than needed to display the relevant items.

In this screenshot, note there is plenty of room for all the items to display, yet a scrollbar is present that allows you to scroll to nothing.  If the saas offerings are removed, the bug goes away.

![screen shot 2017-06-23 at 9 03 12 am](https://user-images.githubusercontent.com/895728/27483343-f862765a-57f2-11e7-9164-39be4887d89c.PNG)

It's very noticeable in Windows (and Linux) where the scrollbars are visible:
![screen shot 2017-06-23 at 9 11 45 am](https://user-images.githubusercontent.com/895728/27483610-27129be6-57f4-11e7-9441-ff58f012fb2a.PNG)

**Comment by jeff-phillips-18** [comment]
This is purposeful. The extra space allows the snap scrolling when selecting a category. See https://github.com/openshift/origin-web-catalog/pull/280

**Comment by rhamilto** [comment]
Understood.  But it's still a bug IMO.
