### ISSUE TITLE
Tiles have a scrollbar when the title is long

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#34]
<img width="208" alt="screen shot 2017-03-24 at 3 25 28 pm" src="https://cloud.githubusercontent.com/assets/1167259/24310397/2b2fd936-10a6-11e7-8449-0015d572f1bc.png">

cc @rhamilto

**Comment by spadgett** [comment]
Assigning to @rhamilto since he is styling these tiles.

**Comment by rhamilto** [comment]
Fixed by #102
