### ISSUE TITLE
Category filter lets you enter empty values

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#341]
The `pf-filter` widget lets you press enter without typing anything, which adds an empty keyword filter.

**Comment by spadgett** [comment]
@dtaylor113 I don't know if this requires changes upstream, but if it's a small fix, would be good to target for 3.6

@jwforres FYI

**Comment by dtaylor113** [comment]
@spadgett, I could do some jQuery to add some minLength validation for the filter input field, but that seems overly complex.  It's a simple fix upstream in the a-pf filter component.  I'll add it there.
Thanks,
Dave

**Comment by jeff-phillips-18** [comment]
@dtaylor113 In the filterChange callback, check the appliedFilters and if a filter is blank, remove it from the list of appliedFilters.

**Comment by dtaylor113** [comment]
@jeff-phillips-18, thanks!  That did the trick.  I'll put up a PR.
