### ISSUE TITLE
Dialog content bounces when focusing inputs on mobile Safari

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#349]
![screencast 2017-06-30 13-00-00](https://user-images.githubusercontent.com/1167259/27746177-2e95e940-5d94-11e7-940b-84460ea24693.gif)

**Comment by rhamilto** [comment]
I'm unable to reproduce as I'm seeing form get zoomed.  Not sure we want the zooming, either?

**Comment by spadgett** [comment]
@rhamilto Are you testing in the console repo? We have styles there that prevent the zooming, although they won't help the catalog if running outside of the console.

**Comment by rhamilto** [comment]
> @rhamilto Are you testing in the console repo? We have styles there that prevent the zooming, although they won't help the catalog if running outside of the console.

Bingo.  That occurred to me right before you replied.  Thanks.

**Comment by rhamilto** [comment]
It appears this only occurs if body is scrolled before entering the form (yes, for some reason body can be scrolled despite the overflow: hidden being added when the panel is open).  I'm not sure if this is the result of testing in the simulator or not.  Need to figure out how to test on an actual device...

**Comment by rhamilto** [comment]
Well, judging by https://stackoverflow.com/questions/41594997/ios-10-safari-prevent-scrolling-behind-a-fixed-overlay-and-maintain-scroll-posi, this looks like a problem regardless of simulator or not.  @spadgett, what's the best way to incorporate javascript in to the catalog?

**Comment by spadgett** [comment]
@rhamilto You probably want to add this to `overlay-panel.controller.ts`. You can inject `$element` as a dependency and then add the listener on `$element` in `$postLink`. Have a look at `services-view.controller.ts` and `saas-list.controller.ts` for some examples where we add listeners.

As an aside, does the Bootstrap modal have this problem? I wonder if we should consider switching to the Bootstrap modal in 3.7 and simply style it to look like our overlay panel. We've had a number of issues like #49, #120, #326 and this one that we might be able to avoid altogether using the Bootstrap modal.

cc @jeff-phillips-18

**Comment by rhamilto** [comment]
@spadgett, I'm struggling with this one.  I think it's time for reinforcements!

**Comment by spadgett** [comment]
Tested with a real device, and this is no longer a problem.
