### ISSUE TITLE
Long, unbroken usernames overflow "My Projects" sidebar

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#388]
![screen shot 2017-08-21 at 9 08 02 am](https://user-images.githubusercontent.com/895728/29520761-6e87d402-8650-11e7-9c4c-49d7e3189b70.PNG)

**Comment by spadgett** [comment]
@amarie401 Can you take a look at this (whenever you wrap up your other bug)? @rhamilto should be able to help if you have questions.

**Comment by amarie401** [comment]
@spadgett I certainly can, thanks!
