### ISSUE TITLE
Projects summary does not show Getting Started area/text

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-catalog#40]

**Comment by spadgett** [comment]
A cluster admin can optionally set up a custom message when you can't create a project. We should make sure the design includes this.

**Comment by jeff-phillips-18** [comment]
@beanh66 Do we have a design for the custom message?

**Comment by beanh66** [comment]
@jeff-phillips-18 In my understanding @serenamarie125 and I had a conversation with @jwforres and the group about the create project button being configurable to handle this use case. So customers can either hide the create project button or take over the button by providing an alternative label and URL. @spadgett Are you doing something different today with a custom message?

**Comment by spadgett** [comment]
@beanh66 There's a custom message the cluster admin can set when users aren't allowed to create projects:

https://docs.openshift.org/latest/admin_guide/managing_projects.html#disabling-self-provisioning

We show the message today in the web console project list when the user has no projects and can't create one.

**Comment by beanh66** [comment]
@spadgett @jeff-phillips-18 Understood, see attached for a design! When the create project button is hidden, that message is displayed underneath the "Getting Started" header on the project panel.
![screen shot 2017-04-12 at 1 56 58 pm](https://cloud.githubusercontent.com/assets/18057044/24972357/3a7ddcac-1f89-11e7-8758-e46305313bb8.png)

**Comment by spadgett** [comment]
We should decide what to do when the user clicks a service in this case since they'll never be able to complete the wizard. (You don't have any projects, and you can't create one.)

cc @serenamarie125

**Comment by spadgett** [comment]
@jeff-phillips-18 We should probably run the message through `linky` since it might have URLs or email addresses
