### ISSUE TITLE
Catalog Filter Panel:  How to display if only one filter?

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#402]
It is projected that the catalog filter panel will have a keyword text input field and a few groups of checkboxes for Vendors and other metadata.  However, at the present time we only have the one keyword input filter.  It has been suggested that if we only have one input box as a filter is should not be on a panel but rather inline with the filter results.  Very similar to what we have/had previously.  We need some uxd input.

@serenamarie125 , @beanh66

**Comment by beanh66** [comment]
Good point @dtaylor113! @cshinn curious if you already considered this piece in your design. If not, should we add to the documentation that the panel is only used at certain times once there is at least one category to filter on or what do you think?

**Comment by cshinn** [comment]
@spadgett I agree. I think that it is better for consistency and ideally we'd have more faceted filters. I think having per-category filters is definitely a good direction to go.

**Comment by spadgett** [comment]
This is not a problem in practice because the templates have a vendor set. It just wasn't showing up (fixed in #410).

Closing because we'll almost always have two filters.
