### ISSUE TITLE
Is "Vendor" the right label for the faceted filter?

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#411]
I am wondering if "Publisher" or "Provider" isn't more accurate. The metadata field is `providerDisplayName`. It looks odd to me that "Red Hat, Inc." is the vendor for ".NET"

![openshift web console 2017-08-31 14-56-55](https://user-images.githubusercontent.com/1167259/29940327-d60f0cb2-8e5c-11e7-9312-56920ebbdf32.png)

@sspeiche @serenamarie125 @pmorie

**Comment by sspeiche** [comment]
Publisher sounds more accurate.

Provider makes me think of a service hosted off platform, like the card requesting designation for not _portable_ services

**Comment by serenamarie125** [comment]
I agree that publisher sounds better.

FYI,I have a new design being posted tomorrow which suggests showing the "publisher" directly under the catalog item in the overlay panel.
