### ISSUE TITLE
Project sidebar can convolute developer name with time since created

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#412]
A list of random projects to illustrate:

![screen shot 2017-09-01 at 10 45 44 am](https://user-images.githubusercontent.com/280512/29975582-e3f1a760-8f04-11e7-8a80-5c32ef281cc3.png)

First two projects look like `developer 19` created the project blank hours ago.

**Comment by spadgett** [comment]
Probably want a `nowrap` around the creation date
