### ISSUE TITLE
Allow launching of a template overlay panel by direct linking to the catalog

### ISSUE THREAD

**Issue by david-martin** [openshift/origin-web-catalog#423]
This feature request is coming from a use case when developing an OpenShift UI extension for Mobile.
The extension shows an extra menu & mobile developer content when in a Project. 
Part of that content provides instructions & a link to the catalog for provisioning supplementary services for the extension. e.g. a Push Notification service.
It would be a better user experience if we could link the user directly to a page that allows provisioning of that service.

So a link like https://192.168.37.1:8443/console/?class=fh-sync-server would open the catalog view and launch the overlay panel for provisioning an instance of the class specified in the param.

**Comment by david-martin** [comment]
@spadgett Does this seem like a reasonable feature request?
I could work on this if you like, given some pointers

**Comment by spadgett** [comment]
@david-martin This seems to be the same request as

https://trello.com/c/w8LiRRSg

> I could work on this if you like, given some pointers

Absolutely. The wizard is opened here.

https://github.com/openshift/origin-web-catalog/blob/master/src/components/landing-page/landing-page.controller.ts#L19

You might be able to just check for a route parameter here and use `$scope.broadcast` to open the panel.

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/landingPage.js#L103

**Comment by spadgett** [comment]
cc @sspeiche
