### ISSUE TITLE
Do not disable catalog filtering input when only one item is available

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-catalog#427]
Disabling when there is only one item is inconsistent with the patternfly pattern and is not intuitive since there is no real need for filtering when there are 2 or 3 or 4 items either.

**Comment by jeff-phillips-18** [comment]
Filtering has changed and this issue is no longer applicable.

**Comment by spadgett** [comment]
@jeff-phillips-18 It is still disabled as far as I can tell, although not a huge issue. (Hard to tell in the screenshot, but the controls are disabled.)

![openshift web console 2017-09-19 11-38-04](https://user-images.githubusercontent.com/1167259/30601094-0f5df150-9d2f-11e7-9658-84cb92df6ca1.png)

**Comment by jeff-phillips-18** [comment]
Ah, ok. I just saw that the original filter box was gonzo. Reopening.
