### ISSUE TITLE
Let admins provide synonyms for the publisher filter

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#429]
I could see values like "Red Hat", "Red Hat, Inc", and "Red Hat, Inc." (with a period) all showing up in the filter panel. Since the OSB API metadata value is `providerDisplayName` rather than a unique identifier, brokers could refer to the same provider in slightly different ways.

We might add a way in constants.js to fix this. For instance, a map of synonyms like

```js
OPENSHIFT_CONSTANTS.PUBLISHER_SYNONYMS = {
  'Red Hat': 'Red Hat, Inc.'
  'Red Hat, Inc': 'Red Hat, Inc.'
};
```

then all of these values would be treated as "Red Hat, Inc." in the filter panel.

cc @serenamarie125 @ncameronbritt @jeff-phillips-18

**Comment by serenamarie125** [comment]
I agree this is an important feature!

I assume this would be reflected in the filter panel and overlay panel.

**Comment by ncameronbritt** [comment]
Totally agree. And as I noted with the search stuff, it would be good to anticipate some of these. 

Related, we should probably also be including vendor in search.

**Comment by dtaylor113** [comment]
So on the filter panel we'd only show the "Red Hat, Inc" for all the synonyms but we'd have to do the opposite of that when applying the filter -we'd have to filter the templates/serviceinstances against all the synonyms.

**Comment by spadgett** [comment]
I was thinking we could do the normalization once in catalog service when
we create the ServiceItem

**Comment by dtaylor113** [comment]
Ok, that works too :-)  -thanks
