### ISSUE TITLE
Allow direct linking to the catalog with a specific category visible/open

### ISSUE THREAD

**Issue by david-martin** [openshift/origin-web-catalog#437]
Related to #423.

This feature will allow a user to arrive on the service catalog screen with a specific category/sub-category selected.
For example, if a user goes to https://mycluster.example.com/?category=databases&subCategory=mysql, the catalog will render as below

![image](https://user-images.githubusercontent.com/878251/30544887-dc4c2890-9c7f-11e7-8012-0288de5b5813.png)

**Comment by david-martin** [comment]
@spadgett Similar to #423, does this seem like a reasonable feature request?

I can put a PR together if it's likely to be accepted

**Comment by spadgett** [comment]
It makes sense to me. We might want to update those query parameters when the selected category changes like we do for other tabs in the web console.

I have a slight preference for `subcategory` without the camel casing.

**Comment by david-martin** [comment]
:+1:  will do

**Comment by david-martin** [comment]
@spadgett Would it make sense to add listeners for 'select-category' and 'select-subcategory' in the catalog https://github.com/openshift/origin-web-catalog/blob/f11248b99ae5d879190e02665d3f50e4a03f21dc/src/components/services-view/services-view.controller.ts#L51-L66,
 and emit those events from the console when data is loaded and if there is a 'category' and 'subcategory' query param?
https://github.com/openshift/origin-web-console/blob/6f40623444af501083edb4979a9b833ccfc5f026/app/scripts/controllers/landingPage.js#L113

Or should that logic be isolated to the catalog only?

**Comment by david-martin** [comment]
@spadgett Any thoughts or points on above comment?
