### ISSUE TITLE
Need to truncate long text in SaaS Offering Tiles

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#45]
Need to use `<truncate-long-text>` in web-catalog's SaaS Offering tiles:

![image](https://cloud.githubusercontent.com/assets/12733153/24458114/fae42e8a-1465-11e7-8d03-20a12741b1c8.png)

**Comment by jeff-phillips-18** [comment]
This directive was already added to origin-web-common:

https://github.com/openshift/origin-web-common/pull/21
