### ISSUE TITLE
CatalogFilter TypeError: cannot set ctrl.keywordFilter.values

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#452]
![screen shot 2017-09-27 at 10 41 28 am](https://user-images.githubusercontent.com/280512/30919796-6f151f00-a370-11e7-95c7-0720c2b0e910.png)
![screen shot 2017-09-27 at 10 41 40 am](https://user-images.githubusercontent.com/280512/30919795-6efeb620-a370-11e7-8de9-64aacf98607b.png)

**Comment by dtaylor113** [comment]
Hi @benjaminapetersen, can you please include steps on how to reproduce?  I'm able to do a global 'Search Catalog" and a Filter from Browse Catalog.

**Comment by benjaminapetersen** [comment]
Let me see if i can reproduce it. I was honestly just typing in the search, i think for "jenkins" or "build pipeline" or something along those lines.  It was not complex.

**Comment by dtaylor113** [comment]
Reproduced it.  Happens when you search when Browse Category is on any category/sub-category other than 'All'.

**Comment by spadgett** [comment]
Thanks @dtaylor113 

I'm going to make this a blocker because it's a reproducible runtime error
