### ISSUE TITLE
Allow passing parameters when creating a binding

### ISSUE THREAD

**Issue by maleck13** [openshift/origin-web-catalog#472]
After provisioning a service, if you want to create a binding, you can click the binding option in the project overview screen. However there doesn't seem to be a way to pass parameters at this point that may be required by the service broker. 
The service catalog and broker api allows for the passing of parameters to the bind API so it seems we should also be able to do this from the UI?
If not service bindings that rely on parameters being passed to work will not work from this ui feature? Is there something I am missing (as in a way to specify binding parameters that the ui can pick up on)?

**Comment by spadgett** [comment]
This will be supported in 3.7 and works in current master. The broker does need to pass back a schema for bind.

https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#schema-object

Implemented in

https://trello.com/c/Sws4p5jU
https://github.com/openshift/origin-web-console/pull/1987

This was not yet implemented in the 3.6 tech preview, however.

**Comment by spadgett** [comment]
Closing as this has been implemented.

**Comment by maleck13** [comment]
@spadgett Thanks for the info
