### ISSUE TITLE
Hide the add to project dropdown if no project

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#477]
I stumbled on this for a second, probably indicating that it could be clearer. Usually if there isn't a choice we make a dropdown into a heading.

I have no projects, should I add to project or create a new? Both? Having no projects (but not realizing it atm since I create & delete them all the time) I found this odd:
![screen shot 2017-10-09 at 2 55 32 pm](https://user-images.githubusercontent.com/280512/31353757-c4a5a4cc-ad01-11e7-9f8e-0babf0afcec4.png)

Hmm, no options, so why is it a drop down?
![screen shot 2017-10-09 at 2 59 37 pm](https://user-images.githubusercontent.com/280512/31353879-41563eb4-ad02-11e7-8998-362ad3fd6a81.png)

Kind of clear, but is still a bit abnormal.
![screen shot 2017-10-09 at 2 59 46 pm](https://user-images.githubusercontent.com/280512/31353884-463dedc8-ad02-11e7-8dff-12d32b7c1e96.png)

I'm open to disagreement here, just pointing it out as we usually don't show a drop-down menu if there isn't actually an item to select.

@spadgett @jeff-phillips-18 @rhamilto

**Comment by dtaylor113** [comment]
What should happen if a user has no projects and doesn't have rights to create a project?
Should we display an appropriate error message under "Add to Project".  In this scenario, the user wouldn't be able to order a service, so the [Next] wizard button should never become enabled.
@benjaminapetersen, @spadgett

**Comment by benjaminapetersen** [comment]
Yeah I would think we should preempt that as well as we can.  They should probably get that message on login, rather than waiting until they click a button that won't let them do anything anyway.  Thoughts?  

@ncameronbritt

**Comment by dtaylor113** [comment]
Hi, when user can only create a project, I have:

![image](https://user-images.githubusercontent.com/12733153/31448812-57de9196-ae73-11e7-99e6-9ef123b83523.png)

Feels like the 'create project' fields should be indented, correct?

**Comment by benjaminapetersen** [comment]
Honestly I would prefer if this was a different step in the wizard, would clear things up a good bit.  Deal with project select/create in a step, then deal with the app being added in the next.  Might just be my opinion, however.

**Comment by spadgett** [comment]
I'm not sure this is better. It looks like the whole form is for creating a project :/

**Comment by jeff-phillips-18** [comment]
@openshift/team-ux-review thoughts?

**Comment by cshinn** [comment]
One option is to disable the dropdown when the only option is to create. Possibly with a small note stating why the dropdown is disabled. That way we don't have to re-organize the page for the different situations, but we also don't waste anyone's time

**Comment by cshinn** [comment]
One option is to disable the dropdown when the only option is to create a new project, possibly with a short note describing why. That way, we don't need to reorganize the page for a single situation and we also don't waste anyone's time

**Comment by serenamarie125** [comment]
I don't think that having it a separate step in the wizard makes sense.

For the case when the user has ability to Create a Project, but there are no existing projects, how about something like this? (hide the drop down and show an instruction)
![screen shot 2017-10-11 at 12 42 59 pm](https://user-images.githubusercontent.com/12504403/31453914-bdc9e556-ae81-11e7-96f6-57689a2ce40c.png)

**Comment by serenamarie125** [comment]
For the case where there ARE existing projects & they can create a new ... you'd still have this
![screen shot 2017-10-11 at 12 44 52 pm](https://user-images.githubusercontent.com/12504403/31454011-0c6aa24a-ae82-11e7-889d-e8edf1bbb76b.png)

**Comment by serenamarie125** [comment]
But then the question is ... when there is only one project allowed, and it has already been created, do we display the dropdown, with that project selected, but disable the dropdown?
![screen shot 2017-10-11 at 12 46 16 pm](https://user-images.githubusercontent.com/12504403/31454097-4d52aab4-ae82-11e7-803c-ad957ac27127.png)

**Comment by serenamarie125** [comment]
@dtaylor113 @benjaminapetersen @spadgett @ncameronbritt @beanh66 @cshinn @jeff-phillips-18 how bout a 👍 or 👎  on each of the 3 items above?

**Comment by dtaylor113** [comment]
Hi @serenamarie125, I think the issue with Case 1 is that the Create Project title seems to also be including the OTHER FIELDS.

**Comment by dtaylor113** [comment]
Here's a screenshot with a little left-hand padding to offset the 'create project' form:

**Can only Create Project:**
![image](https://user-images.githubusercontent.com/12733153/31455796-c45a5e82-ae86-11e7-8ee4-d32ce5524a03.png)

**Choosing to Create Project:**
![image](https://user-images.githubusercontent.com/12733153/31455994-0adca234-ae87-11e7-996c-61b3e34ec3fd.png)

**Selecting a Project:**
![image](https://user-images.githubusercontent.com/12733153/31456117-1858544e-ae87-11e7-8f4b-e30d34ffae50.png)

**Comment by beanh66** [comment]
@benjaminapetersen I just realized we have the same problem with the version dropdown. I have selected a few catalog items that only have a single version, but this option still appears in a dropdown where there are no other versions available. 

I agree with @cshinn! My preference for these cases would be to show the default selection (Create Project) and disable the dropdown with a hover message explaining why.

**Comment by jeff-phillips-18** [comment]
I agree with @cshinn as well, but maybe "Create Project (no existing projects)" or some such thing.

**Comment by benjaminapetersen** [comment]
We probably also should deal with "There are no projects and you can't create projects".

**Comment by dtaylor113** [comment]
Seems like we're liking @cshinn suggestion of disabling the dropdown when there is only 'Create Project'.  I'll work on that.

**Comment by dtaylor113** [comment]
**Can only create project**
![image](https://user-images.githubusercontent.com/12733153/31461332-3630f09c-ae97-11e7-8f77-8dfb6aa62557.png)

**Only one project and cannot create**
![image](https://user-images.githubusercontent.com/12733153/31461496-aa1db4d6-ae97-11e7-9a8f-7e65ce616181.png)

**No existing projects and cannot create projects**
![image](https://user-images.githubusercontent.com/12733153/31462137-98f28482-ae99-11e7-9059-ddca8dd94b4e.png)
* Not sure this is the best treatment/message here, but it's a start.  Kinda want to add a 'Please contact your cluster administrator' to the message.

**Comment by serenamarie125** [comment]
@dtaylor113 I'm good with the first 2 scenarios.

As for the No existing projects & cannot create ... can that actually happen?  Hoping NOT :D

**Comment by spadgett** [comment]
@serenamarie125 It can happen :/ Usually in organizations where they want you to request projects through some process outside of OpenShift. You can disable create project in the UI.

**Comment by cshinn** [comment]
That seems like a situation where it would be good to let the admin put a url or email address or something in the message

**Comment by dtaylor113** [comment]
> That seems like a situation where it would be good to let the admin put a url or email address or something in the message

Hi, @spadgett, @cshinn suggestion seems like a good idea, but how often does this occur? -thanks

**Comment by spadgett** [comment]
> That seems like a situation where it would be good to let the admin put a url or email address or something in the message

We support custom messages and add it to the projects sidebar. We could show it here as well.

**Comment by dtaylor113** [comment]
Created #494

**Comment by benjaminapetersen** [comment]
I think its a little confusing yet for "Create Project" to appear in the disabled input.  Maybe "No existing projects" should be the text, though then we need a "create project" heading, which brings back the issue @spadgett mentioned.   I have no strong feelings on the tooltip.  

<img width="341" alt="screen shot 2017-10-12 at 11 33 52 am" src="https://user-images.githubusercontent.com/280512/31504768-4027ebf0-af41-11e7-9044-21e6eb5019d4.png">

**Comment by ncameronbritt** [comment]
Also odd that the disabled input is a required field.

**Comment by ncameronbritt** [comment]
What about making Add to Project and Configuration both headers:
<img width="858" alt="screen shot 2017-10-12 at 4 45 22 pm" src="https://user-images.githubusercontent.com/8974593/31519751-5f0df494-af71-11e7-901a-c8dbaef84625.png">
<img width="857" alt="screen shot 2017-10-12 at 4 45 49 pm" src="https://user-images.githubusercontent.com/8974593/31519756-637e0884-af71-11e7-83cd-f44b86a3f765.png">


And I think we should block a user from going past the info screen if there are no projects and they don't have permission to create one. We couldn't do that before because the info and configuration were the same step. We should be able to now.

**Comment by dtaylor113** [comment]
:+1:  sounds good.  I believe currently the [Next] button is disabled until they have a valid project specified.

**Comment by spadgett** [comment]
Note that we use this widget in a bunch of different dialogs now. We should check how it looks in them all.

**Comment by serenamarie125** [comment]
@dtaylor113 can you wait on this for a bit?  I'd like to have consensus from the Design side before you continue to change things

**Comment by beanh66** [comment]
@dtaylor113 @spadgett @benjaminapetersen the consensus from designers is the following: 
![new mockup 1a](https://user-images.githubusercontent.com/18057044/31561668-9f6a68d2-b026-11e7-8db8-b31ea5fd576d.png)
![new mockup 1b](https://user-images.githubusercontent.com/18057044/31561669-9f7761c2-b026-11e7-8cc2-49df650ca314.png)
![new mockup 1c](https://user-images.githubusercontent.com/18057044/31561670-9f854f62-b026-11e7-9ddf-b90bb0aef920.png)

Essentially we are saying (1) projects section should always be at the top of the form (moving version down below project stuff) (2) projects section should always have a divider line under it (3) when “Create Project” is the only option, the dropdown should disappear and the subheader “Create Project” should replace it

Note: this styling of the project section would also apply to the Deploy Image and Import YAML wizards as well.

**Comment by dtaylor113** [comment]
@beanh66, looks good.  Where does the "contact your cluster administrator" link goto?  Are we saying that should be a custom/extension message?

**Comment by spadgett** [comment]
@dtaylor113 It should be the request project message that the admin configures. See

https://github.com/openshift/origin-web-catalog/blob/master/src/components/projects-summary/projects-summary.html#L23

https://github.com/openshift/origin-web-catalog/blob/master/src/components/projects-summary/projects-summary.controller.ts#L86-L109

**Comment by spadgett** [comment]
@dtaylor113 Please update all of these dialogs when you make this change.

```
origin-web-console/app/views/directives/deploy-image.html
2:  <select-project ng-if="!project" selected-project="input.selectedProject" name-taken="projectNameTaken"></select-project>

origin-web-console/app/views/directives/process-template.html
4:      <select-project ng-if="!$ctrl.project" on-project-selected="$ctrl.onProjectSelected" available-projects="$ctrl.availableProjects" selected-project="$ctrl.selectedProject" name-taken="$ctrl.projectNameTaken"></select-project>

origin-web-console/app/views/directives/from-file.html
1:<select-project ng-if="!project" selected-project="input.selectedProject" name-taken="projectNameTaken"></select-project>

origin-web-catalog/src/components/order-service/order-service-configure.html
4:      <select-project selected-project="$ctrl.selectedProject" name-taken="$ctrl.nameTaken"></select-project>

origin-web-catalog/src/components/create-from-builder/create-from-builder-configure.html
18:      <select-project selected-project="$ctrl.selectedProject" name-taken="$ctrl.projectNameTaken"></select-project>
```

**Comment by dtaylor113** [comment]
Thanks @spadgett, so it looks like `$ctrl.newProjectMessage' is set after a failed `ProjectsService.canCreate()`.  Does the project request message come from the returned `data.details.causes', and/or is it set via some Constants like the other custom messages/HTML?

**Comment by spadgett** [comment]
It's in `data.details.causes`

**Comment by beanh66** [comment]
Thanks @spadgett :+1:

**Comment by dtaylor113** [comment]
Hi, just want to verify that this is how we want to display when user has existing projects and can create projects, and chooses to create a project:

![image](https://user-images.githubusercontent.com/12733153/31618531-31b10508-b260-11e7-995a-1649b5857eb3.png)

Also, is there a way to taper the start and end of the bottom border like the mockups suggest?  If so, pls send the css -thanks

**Comment by cshinn** [comment]
@dtaylor113 I believe it already does that.

**Comment by dtaylor113** [comment]
Hi @cshinn, @beanh66, @spadgett,
Latest screenshots located here: #493
