### ISSUE TITLE
Safari: SVG icons too small in catalog

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#478]
The look fine in Chrome, but the icons are much smaller in Safari.

![screen shot 2017-10-10 at 8 41 57 am](https://user-images.githubusercontent.com/1167259/31387189-884fb95e-ad97-11e7-9270-de91109422a2.png)

**Comment by spadgett** [comment]
Chrome, IE, and Firefox are fine. It only seems to be a problem in Safari.

**Comment by rhamilto** [comment]
My testing indicates they are small in IE11, too.

**Comment by spadgett** [comment]
> My testing indicates they are small in IE11, too.

I'm probably wrong then. They're showing up at least :)
