### ISSUE TITLE
Info page in catalog should show publisher

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#479]
Right now the publisher information is not shown when you click an item to provision it.

**Comment by rhamilto** [comment]
"Publisher information" === spec.externalMetadata.providerDisplayName?

<img width="463" alt="screen shot 2017-10-10 at 12 05 16 pm" src="https://user-images.githubusercontent.com/895728/31397176-4f287dd4-adb3-11e7-9237-df912b096eef.PNG">

**Comment by spadgett** [comment]
You should be able to use `$ctrl.serviceClass.vendor` in the dialog.

**Comment by rhamilto** [comment]
@ncameronbritt, I'm assume we want to change the icons/images from horizontally centered to top aligned?

<img width="908" alt="screen shot 2017-10-10 at 12 18 57 pm" src="https://user-images.githubusercontent.com/895728/31398076-bef66656-adb5-11e7-80c2-a2d4bb8fcd0b.PNG">
<img width="929" alt="screen shot 2017-10-10 at 12 19 26 pm" src="https://user-images.githubusercontent.com/895728/31398077-bf046e40-adb5-11e7-9b9a-5a1bbc4c65a2.PNG">

**Comment by ncameronbritt** [comment]
Yeah, I think so. What do you think @openshift/team-ux-review ?

**Comment by rhamilto** [comment]
@openshift/team-ux-review, per http://openshift.github.io/openshift-origin-design/web-console/5-components/order-from-catalog#1---information-step, tags should also be muted?

<img width="916" alt="screen shot 2017-10-10 at 12 29 13 pm" src="https://user-images.githubusercontent.com/895728/31398349-ab679d66-adb6-11e7-8f3a-c666abc6aa64.PNG">

**Comment by ncameronbritt** [comment]
@jhaines?

**Comment by spadgett** [comment]
@jennyhaines ^

**Comment by jennyhaines** [comment]
@spadgett @rhamilto @ncameronbritt - I think the top alignment of the logo is a nice change. Changing the tags to be muted is also a good idea. I think it helps set it apart from the publisher name.

**Comment by beanh66** [comment]
Agreed @jennyhaines, top aligned icons and muted tags looks great.
