### ISSUE TITLE
Icons are too big when navigating to the advanced options for catalog items

### ISSUE THREAD

**Issue by beanh66** [openshift/origin-web-catalog#492]
Selecting the advanced options link from the ordering panel brings users to the old ordering page, but the new icons are too large. 
![screen shot 2017-10-12 at 9 18 12 am](https://user-images.githubusercontent.com/18057044/31498442-ea243774-af2f-11e7-9740-8b3fab6c8d08.png)

FYI @spadgett

**Comment by spadgett** [comment]
Should be fixed by https://github.com/openshift/origin-web-console/pull/2245

@rhamilto can you confirm?

**Comment by rhamilto** [comment]
> @rhamilto can you confirm?

Confirmed.
