### ISSUE TITLE
Add custom msg for when there are no projects and user cannot create projects

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#494]
This is for the `<select-projects>` component.

**No existing projects and cannot create projects**
![image](https://user-images.githubusercontent.com/12733153/31462137-98f28482-ae99-11e7-9059-ddca8dd94b4e.png)

Seems like a situation where it would be good to let the admin put a url or email address or something in the message.  We support custom messages and add it to the projects sidebar. We could show it here as well.

**Comment by dtaylor113** [comment]
Follow up issue #494

**Comment by beanh66** [comment]
@dtaylor113 Note from issue #477 we decided to go with an empty state for this page when the user cannot create or select a project.

![new mockup 1c](https://user-images.githubusercontent.com/18057044/31562278-d16aa4d0-b028-11e7-9535-5c9d8a9d72f5.png)
