### ISSUE TITLE
White background visible at bottom of landing page on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#495]
![screen shot 2017-10-13 at 7 27 29 am](https://user-images.githubusercontent.com/1167259/31544288-1612a4a2-afe8-11e7-8e64-f5e561689eb4.png)

**Comment by spadgett** [comment]
Also there's a weird notch at the top of the page (see screenshot). Can you fix that @rhamilto ?

**Comment by rhamilto** [comment]
> Also there's a weird notch at the top of the page (see screenshot). Can you fix that @rhamilto ?

LOL
