### ISSUE TITLE
Should not show plan description on info page when there's more than one plan

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#499]
We show the plan description on the info page when there's only one so that the description isn't lost if there is important information. This isn't a problem if there is more than one plan, so we don't need to show it here. It might be misleading in some cases. Here there is a plan option that uses persistent storage instead of ephemeral, but the info page makes it sound like it's only ephemeral.

![openshift web console 2017-10-16 10-41-10](https://user-images.githubusercontent.com/1167259/31617989-b68ad27e-b25e-11e7-8036-671f5bebf5f1.png)

**Comment by jeff-phillips-18** [comment]
@spadgett I didn't think we show the plans page when there is only 1 plan?

**Comment by jeff-phillips-18** [comment]
nvm, you are sayin on the info page... my bad
