### ISSUE TITLE
Checkbox alignment on catalog filters is off

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#504]
The alignment on the filter checkboxes seems off in a couple of ways.  I can't decide whether the left indention makes sense, or maybe it is just indented too far.  But then the checkbox is not correctly aligned with its label.

![screen shot 2017-10-17 at 2 55 15 pm](https://user-images.githubusercontent.com/1467629/31683654-8f1f5aaa-b34b-11e7-85b0-767299b54691.png)

**Comment by spadgett** [comment]
@dtaylor113 We should be using `<div class="checkbox">` around the checkbox if possible

**Comment by serenamarie125** [comment]
@dtaylor113 do we know if this is a PatternFly issue or specific to OpenShift?

**Comment by spadgett** [comment]
It seems to be specific to OpenShift.

https://github.com/openshift/origin-web-catalog/blob/ad74ff6bfaba0e1888f1abb7459b5fa8fbb020e0/src/components/catalog-filter/catalog-filter.html#L19-L26
