### ISSUE TITLE
Icons in recently viewed circles seem too small

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#506]
The icons in recently viewed seem like they are on the small side, is it possible to increase it?

![recenticons](https://user-images.githubusercontent.com/1467629/31685910-b1f850e8-b352-11e7-944e-0218cf724b17.png)

**Comment by jwforres** [comment]
@openshift/team-ux-review

**Comment by ncameronbritt** [comment]
I feel like the monochrome logos might have looked a little better in this context/at this size.

**Comment by beanh66** [comment]
@ncameronbritt that might be strange to see two different versions of catalog logos within the same page. I would vote for keeping the colored icons and just increasing the size slightly if needed, but curious what other think! @cshinn @serenamarie125 @jennyhaines

**Comment by ncameronbritt** [comment]
I wasn't suggesting that, @beanh66. Just saying that I think this looked a little better before we switched to the color icons. I think the size could definitely be increased.

**Comment by serenamarie125** [comment]
Feels to me that the size has gotten smaller since we changed to full color. I think that there was an issue filed by @spadgett on that as well a while back?  Unsure if that has been fixed yet.  

I agree, keep color and see if we can get them back to the size they were previously.

**Comment by jennyhaines** [comment]
@jwforres @serenamarie125 @beanh66 - It looks like those icons in the screenshot are 24x24px, but I think they could increase up to 30x30px.

**Comment by spadgett** [comment]
@jennyhaines suggested making the recently viewed icons 32px in https://github.com/openshift/origin-web-console/pull/2313
