### ISSUE TITLE
Search and sidebar in <landing-page> should have fixed positioning at the application level

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#51]
#47 undid the fixed positioning of these elements because the positioning was done at the component level.  Moving the positioning to the [application level](https://github.com/openshift/origin-web-catalog/blob/master/app/app.less) keeps the components context-agnostic, thus easing reuse in places like origin-web-console.

**Comment by spadgett** [comment]
Sidebar has fixed positioning again. Just need to fix the search input.

cc @cshinn
