### ISSUE TITLE
Filter panel covers first (and sometimes only) match

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#536]
In this case, the only match is obscured behind the filter dropdown.

![openshift web console 2017-10-24 18-05-50](https://user-images.githubusercontent.com/1167259/31970492-18fd70c8-b8e6-11e7-9bba-6b560216c908.png)

@openshift/team-ux-review @dtaylor113 @jwforres

**Comment by spadgett** [comment]
Note that the filter panel does not close when you click a checkbox, so it would be easy to miss.

**Comment by serenamarie125** [comment]
eek @spadgett this is a tough one.  The good news is that the filter bar has a "1 of 36 items" indicating that there is an existing item.

I don't think it makes sense to automatically close after checking one item, although we have to figure out some kind of solution! nice catch finding this!

**Comment by serenamarie125** [comment]
FYI - created a design story in our Jira board to look into this, and post a solution here once complete: https://patternfly.atlassian.net/browse/OSUX-231

**Comment by dtaylor113** [comment]
We could make the panel background somewhat transparent.

**Comment by serenamarie125** [comment]
@cshinn just want to make sure you saw the above comment ^^

**Comment by cshinn** [comment]
![screen shot 2017-10-25 at 10 35 18 am](https://user-images.githubusercontent.com/3300756/32004643-4992f4bc-b970-11e7-8559-18e111178d14.png)
![screen shot 2017-10-25 at 10 35 06 am 1](https://user-images.githubusercontent.com/3300756/32004650-4c7a7d3a-b970-11e7-8e37-a15f25514fe2.png)
![screen shot 2017-10-25 at 10 35 29 am](https://user-images.githubusercontent.com/3300756/32004654-4df9d2dc-b970-11e7-9d9d-0ac5cb1757a0.png)

Here are some screenshots with the overlay at 80, 90, and 95% transparency

**Comment by jwforres** [comment]
imo anything less than 95% interferes with the text for the filters and makes it hard to read

**Comment by beanh66** [comment]
@jwforres agreed, I think 95% works just fine @cshinn.

**Comment by serenamarie125** [comment]
I think 95% looks good as well!  Thanks @cshinn

**Comment by dtaylor113** [comment]
> Here are some screenshots with the overlay at 80, 90, and 95% opacity

Hi @cshinn, do you happen to recall what css and property you used?  -thanks :-)

**Comment by cshinn** [comment]
@dtaylor113 the .95 that your screens show looks pretty much the same as the .95 in the above screens to me. Do they look different on your monitor?

**Comment by dtaylor113** [comment]
@cshinn They do look the same to me.  I'm advocating for the 90% one.

**Comment by cshinn** [comment]
@dtaylor113 I ran the .95 by several people with different screen configurations and they were all able to see the icon and text through the dropdown. I don't think the goal is for it to be totally legible, just for there to be "something" that is detectable behind the dropdown

**Comment by dtaylor113** [comment]
Ok, sounds good  -thanks
