### ISSUE TITLE
Quick Search "active state" on Landing Page is not very apparent

### ISSUE THREAD

**Issue by jennyhaines** [openshift/origin-web-catalog#558]
Looking at the active state of the search box, it seems that the bright blue box shadow around the field gets lost. I wonder if this is due to a "multiply" blending mode, or just low opacity on the box shadow? 

It would improve the usability to bump up the brightness of that box shadow from this current implementation (screenshot one) to this proposed design (screenshot two):

Current Implementation
![current](https://user-images.githubusercontent.com/24898297/32575570-6a3c2b74-c4a2-11e7-96e1-6defeddbac4d.png)

Proposed
![proposed](https://user-images.githubusercontent.com/24898297/32575589-73eb9114-c4a2-11e7-9cc8-8b679df4e194.png)

**Comment by jennyhaines** [comment]
^ @jwforres @spadgett

**Comment by sg00dwin** [comment]
Hi @jennyhaines, Let me know if this focus example works for you. The following colors were used.

```
&:focus {
        border-color: @color-pf-blue-200;
        box-shadow: 0 0 6px @color-pf-blue-100;
      }
```
![catalog-search-input-hover](https://user-images.githubusercontent.com/1874151/32917950-b85a145e-caee-11e7-9295-81ba5caf0838.gif)
Animation of focus active

**Comment by jennyhaines** [comment]
@sg00dwin - I like that the box shadow spreads to 6px, I just am unsure of the super light pf-blue-100. I think it should be pf-blue-200 instead for an increase in saturation. Do you mind showing what that would look like? (I know it would be less contrasty.) If it is really not showing up well at pf-blue-200, maybe increasing from 6px to 8px might help?

**Comment by sg00dwin** [comment]
@jennyhaines Here are is a comparison of the 2 blues at 8px. 

`box-shadow: 0 0 8px @color-pf-blue-200`
<img width="643" alt="screen shot 2017-11-20 at 3 42 28 pm" src="https://user-images.githubusercontent.com/1874151/33040572-73e31ae6-ce09-11e7-98d9-59d8068dbf13.png">

`box-shadow: 0 0 8px @color-pf-blue-100`
<img width="632" alt="screen shot 2017-11-20 at 3 44 25 pm" src="https://user-images.githubusercontent.com/1874151/33040650-b69234ee-ce09-11e7-88c0-9305febbfe96.png">

**Comment by rhamilto** [comment]
@jennyhaines, do you have recommendation based on @sg00dwin's screenshots?

**Comment by sg00dwin** [comment]
Our current default  active state `input` box-shadow color is so close to the blue shade in background image that it would seem the effect needs to be considerably lighter or darker to bring forth the contrast.

Personally, if we are going with a light 'glow' effect I think 3 works best. And for a darker 'glow' effect 5.

**Comment by jennyhaines** [comment]
@sg00dwin @rhamilto - Just got back from PTO! (Sorry for the holdup.) I think the lighter option with the border color works well. (Option #3) That border color helps to make it more apparent that the search box was selected. Thank you for mocking these up! 

FYI: @serenamarie125

**Comment by rhamilto** [comment]
Option 3 implemented in https://github.com/openshift/origin-web-catalog/pull/564
