### ISSUE TITLE
Wrong builder version is selected by default

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#573]
The most recent version should be selected by default.

![openshift web console 2017-11-29 09-53-20](https://user-images.githubusercontent.com/1167259/33381198-5048efd2-d4eb-11e7-8673-0e18632c9865.png)

We should retain the server ordering since it uses semver to order the tags. Most recent should be at the top of the select. See https://github.com/openshift/origin-web-console/pull/302

cc @jwforres

**Comment by spadgett** [comment]
It looks like we are preserving the tag order that comes from the server.

@bparees I thought status tags were sorted so that the newer tags were first in the array according to semver. Did something change here?

**Comment by bparees** [comment]
@miminar recently changed the import logic, it's possible his changes affected this.

**Comment by spadgett** [comment]
Opened origin issue https://github.com/openshift/origin/issues/17552
