### ISSUE TITLE
npm run start fails with error message

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#591]
The following error is displayed:

```bash 
ERROR in ./src/components/update-service/update-service.controller.ts
(246,63): error TS2345: Argument of type 'string[][]' is not assignable to parameter of type 'Many<PropertyName>'.
  Type 'string[][]' is not assignable to type 'PropertyName[]'.
    Type 'string[]' is not assignable to type 'PropertyName'.
      Type 'string[]' is not assignable to type 'symbol'.

ERROR in ./src/components/update-service/update-service.controller.ts
(247,45): error TS2345: Argument of type 'string[][]' is not assignable to parameter of type 'Many<PropertyName>'.
  Type 'string[][]' is not assignable to type 'PropertyName[]'.
```

I haven't tried to run the catalog standalone in a good while, so I'm not sure if this is a legitimate error or if standalone serve has fallen by the wayside (ie, works fine if running with `bower link` to console).  

@jeff-phillips-18 @spadgett @jwforres

**Comment by dtaylor113** [comment]
Hi @benjaminapetersen,  have you run `npm install` and `bower install` recently?  It runs fine with `bower link` to console -seems strange.  Catalog doesn't use Console as a dependency.  The error message seems Typescript related, which Console doesn't use.  I'll try to reproduce.  -thanks

**Comment by benjaminapetersen** [comment]
@dtaylor113 yup, ran both installs & was running the catalog outside of the console.  Def is a typescript error.  Going to look at it some more this morning as well.

**Comment by dtaylor113** [comment]
@benjaminapetersen, I was able to reproduce when I was using nvm 6.9.0 (npm 3.10.8, node 6.9.0).  I did 
```
nvm use 6.7.0
rm -rf node_modules
rm -rf bower_components
npm install
bower install
npm start
```
and it compiled and ran with no errors.  (npm 5.4.2, node 6.7.0)

**Comment by jeff-phillips-18** [comment]
Just a missing type def on `originalSecretKeys`

**Comment by benjaminapetersen** [comment]
@jeff-phillips-18 just saw your irc message from fri:

    make sure you have @types/lodash version 4.14.77

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen Yeah, not sure if that would fix it but I have a fix PR up now anyhow.
