### ISSUE TITLE
The web catalog project should use real types in typescript

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-catalog#593]
Lots and lots of definitions that simply use 'any' rather than the appropriate types. It would be beneficial to go through and replace as many 'any' declarations with the correct type.

**Comment by benjaminapetersen** [comment]
Just adding a comment here as well, I'd love to see a file or two that follow best practices for `bool`, `sting`, etc, as well as what to do about `interfaces` or functions that require a specific singleton, such as `DataService`.  

I don't mind working on tech debt items with mini-PRs on the side, but I'm pretty fresh to TS yet so if anyone has a good idea about how to do this & could kick off a small PR, that would def be helpful.

**Comment by dtaylor113** [comment]
I don't know about the more advanced topics you mentioned, but this is a good reference for the basic types:   https://www.typescriptlang.org/docs/handbook/basic-types.html.

**Comment by dtaylor113** [comment]
The Catalog app. uses some interesting types  `public scope: ng.IScope;`:
https://github.com/openshift/origin-web-catalog/blob/master/test/utils/ComponentTest.ts#L8

**Comment by benjaminapetersen** [comment]
Yeah thats helpful.  `ICompileService` implies you prob have to do an interface `IDataService` to require `DataService`, I wonder if there is away to get around boilerplate interfaces for singletons.
