### ISSUE TITLE
UI-bootstrap error 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#600]
While adding `node.js` to my project, I found this error in my console:

![screen shot 2017-12-14 at 9 57 17 am](https://user-images.githubusercontent.com/280512/33998490-a154a882-e0b5-11e7-9aec-f930cf63a41a.png)

Not exactly sure how or why, looks like the kind of thing that happens when async things get out of sync.  Will report more if I experience it again.

**Comment by dtaylor113** [comment]
Hi @benjaminapetersen, is this still an Issue?

**Comment by benjaminapetersen** [comment]
Ha, no idea.  I haven't seen it recently.  I assume we can close... if it happens again can reopen.
