### ISSUE TITLE
"Clear filters" link within empty state results always redirects to landing page, even if you're not on the landing page 

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#601]
When clicking the "Clear filters" link within the empty state results, redirection to the landing page always occurs.  If I'm clicking the link when in a project, I would expect to stay within the project.

![screen shot 2017-12-14 at 4 16 15 pm](https://user-images.githubusercontent.com/895728/34014774-5efd8a1e-e0ea-11e7-8f0a-41de2a0d62af.PNG)

**Comment by rhamilto** [comment]
QE also reported this as https://bugzilla.redhat.com/show_bug.cgi?id=1533363

**Comment by dtaylor113** [comment]
Fixed in angular-patternfly v4.13.1.  Need to cut a console PR which updates a-pf dependency from 4.11.8 to 4.13.1.  Need to test a-pf wizard, pfPanelFilter, and pfListView changes, as well as the fix for this.
