### ISSUE TITLE
Demo App fails to start using `npm start`

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#621]
Dev server starts up and Catalog Home/Landing page is shown for a sec, then redirects to:

`https://localhost:8443/oauth/authorize?client_id=openshift-web-console&response_type=token&state=eyJ0aGVuIjoiL2hvbWUiLCJub25jZSI6IjE1MTYxMjg0MTU4MTktMTQ3NTg4MTc2NjQxNDY4MDg3NTUxNzM1MTY1MjE5ODA0MzU3MDEzNTUyNzI1NjI4MTU3MTczODM0NjM5MDM2MzgyOTEzMzQ1NzYxNjYxIn0&redirect_uri=https%3A%2F%2Flocalhost%3A9001%2Foauth`

Which results in the following text displayed on the web page: 

`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"eyJ0aGVuIjoiL2hvbWUiLCJub25jZSI6IjE1MTYxMjg0MTU4MTktMTQ3NTg4MTc2NjQxNDY4MDg3NTUxNzM1MTY1MjE5ODA0MzU3MDEzNTUyNzI1NjI4MTU3MTczODM0NjM5MDM2MzgyOTEzMzQ1NzYxNjYxIn0"}`

I'm not sure why the Catalog mock app should be trying to authenticate with `localhost:8443`?

**Comment by rhamilto** [comment]
@dtaylor113, per https://github.com/openshift/origin-web-catalog#showcase-application, the correct command is `npm run start`.  It works for me.

**Comment by dtaylor113** [comment]
`npm run start` results in the same error for me :-(

**Comment by spadgett** [comment]
You either need to run with mock data or patch the oauth client to allow localhost:9001

**Comment by spadgett** [comment]
See https://github.com/openshift/origin-web-catalog#showcase-application

**Comment by dtaylor113** [comment]
Thanks @spadgett, that did the trick, I had forgotten that step :)
