### ISSUE TITLE
Show APB version when clicking on item

### ISSUE THREAD

**Issue by josemigallas** [openshift/origin-web-catalog#624]
It would be very useful to be able to see the version of APBs before deploying a service. Somewhere here:

![screen shot 2018-01-24 at 11 19 11](https://user-images.githubusercontent.com/11672286/35332450-44f33470-010b-11e8-87c9-5592bbf7653b.png)

It is very annoying to deploy the whole thing just to see that I don't have the APB I expected.

**Comment by spadgett** [comment]
cc @jwmatthews

**Comment by matzew** [comment]
+1  this would be general useful, to see some sort of "versioning" info there

**Comment by matzew** [comment]
I generally find it also nasty that, if you build an _existing_ apb locally and directly push it, that it shows up twice.

sure one comes from the dh org that is configured (e.g. aerogearcatalog), and the one that's new comes from the local registry, pretty hard to determine which is what :)
