### ISSUE TITLE
ng-includes for the wizard don't work properly outside of the catalog repo

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#64]
cc @jeff-phillips-18 @jwforres 

<img width="657" alt="screen shot 2017-03-31 at 7 43 42 am" src="https://cloud.githubusercontent.com/assets/1167259/24549100/cf45875c-15e5-11e7-8a98-a79dda5e340e.png">

**Comment by dtaylor113** [comment]
Hi @spadgett , are there any error messages in the console?

**Comment by spadgett** [comment]
@dtaylor113 No, it just doesn't load the views. Instead it loads the whole page inside the wizard.

**Comment by jeff-phillips-18** [comment]
It is a webpack issue. I believe i have a fix. @spadgett, if I put up a PR can you test it easily? Otherwise I can work through it.

**Comment by spadgett** [comment]
@jeff-phillips-18 I can test.

**Comment by spadgett** [comment]
@dtaylor113 No errors, it's just not resolving the view. It's loading the whole page instead.

<img width="1007" alt="screen shot 2017-03-31 at 8 52 18 am" src="https://cloud.githubusercontent.com/assets/1167259/24551158/79bf35c6-15ef-11e7-8757-708edb42e1e1.png">

**Comment by jeff-phillips-18** [comment]
@spadgett still working on it, realized my fix wouldn't work.

**Comment by jeff-phillips-18** [comment]
Fixed by #73
