### ISSUE TITLE
Bump angular-ui-router dependency version to fix node engine compatibility issue

### ISSUE THREAD

**Issue by TheRealJon** [openshift/origin-web-catalog#654]
Currently, the angular-ui-router package version is set to 1.0.0-beta.1. This version has a bug which causes the package to fail the node engine compatibility test: https://github.com/angular-ui/ui-router/issues/3086

When installing origin-web-catalog with Yarn, this causes a failure unless you use the `--ignore-engines` flag.

**Comment by spadgett** [comment]
@dtaylor113 Do you know why this isn't only a dev dependency? I think it's only used for the sample app?

**Comment by spadgett** [comment]
cc @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
Not sure why it was made a dependency (probably my mistake early on), it definitely should only be a devDependency.

**Comment by spadgett** [comment]
/assign @TheRealJon 

@TheRealJon can change it to a dev dependency?

**Comment by spadgett** [comment]
This has since been fixed by #655

/close
