### ISSUE TITLE
The modal wizard utilized in the Service Catalog does not support keyboard shortcuts

### ISSUE THREAD

**Issue by serenamarie125** [openshift/origin-web-catalog#673]
The modal wizards utilized when selecting an item in the Service Catalog should support keyboard shortcuts.  Currently when the modal wizard is issued, nothing in the wizard has focus by default.

For each page in the wizard, some element should have focus.  The @openshift/team-ux-review should provide input for this.

Once you get to the configuration step, if you select an item, you can then traverse through the form, continue to Tab to the Next button & hit the space key to proceed to the next page.  But once you get to the next page, nothing has default focus.

**Comment by serenamarie125** [comment]
When on the Information page, the Next page should have focus.
When on the Configuration page, the first field should have focus.

Notes:
Move to the next field on a page. | Tab
Return to the previous field on a page. | Shift+Tab
Perform a button action | Space
Move to the next selection in a list. | Down arrow
Move to the previous selection in a list. | Up arrow

**Comment by serenamarie125** [comment]
@spadgett FYI

**Comment by serenamarie125** [comment]
@jeff-phillips-18 can you take a look at this?

**Comment by jeff-phillips-18** [comment]
will do

**Comment by jeff-phillips-18** [comment]
@serenamarie125 For the binding step, since there is a default (do not bind), should focus should be on the `Create` button?

**Comment by serenamarie125** [comment]
That's a good question @jeff-phillips-18.  As a general rule, I would suggest the following:
- When no input fields exist, default focus should be on the primary action button of the wizard/modal
- When one or more input fields exist, regardless if there are default values, default focus should be on the primary action button

When tabbing through input fields, the order should be depending on the field placement.  (top to bottom, left to right )

Once the last input field has focus, tabbing will bring you to the primary action of the wizard button bar (Next in this case), then to the Back button, and then the Cancel button.  Tabbing once more will loop back to the first input field on the modal wizard.  (Note that the behavior would be the same for any modal, the action buttons would just differ).

<img width="857" alt="screen shot 2018-04-20 at 8 35 17 pm" src="https://user-images.githubusercontent.com/12504403/39078645-70441e88-44da-11e8-8cf7-cdb7d07c741c.png">

Note that this also means if the focus is on the first input field and all fields have default values, <Shift>Tab will bring them to the Cancel button, then the Back button, and then the Next button, which will be more efficient than tabbing through a form with a lot of input fields.

Also note that if an input field or button  is disabled, it will be skipped and not receive focus.

**Comment by jeff-phillips-18** [comment]
@serenamarie125 Is it required skip all the defaulted fields? That seems a bit strange to me as a keyboard-less user would not be able to change the defaulted values.

Also, above you state the tab order as Next -> Back -> Cancel, and later Cancel -> Back -> Next.
Shouldn't the order stay consistent? Currently, it is set to Cancel -> Back -> Next (standard button tab order by placement).
