### ISSUE TITLE
config.local.js should not be tracked

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#8]
In origin-web-console, we have `config.js` and `config.local.js`. `config.local.js` is added to `.gitignore` and is for changes specific to your env that you don't want to commit. `config.js` is used when `config.local.js` is not found.

https://github.com/openshift/origin-web-console/blob/master/Gruntfile.js#L525-L536

We should do the same here (or at least remove `config.local.js` and use `config.js`).

cc @jeff-phillips-18

**Comment by dtaylor113** [comment]
Hi, this has been addressed with PR #9
