### ISSUE TITLE
Ensure scrollbars properly indicate scrollable regions

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#84]
With #83, the sidebar's positioning was fixed.  As a result of that positioning and the move of the scrollbar to the inner contents of the page, it's not immediately obvious that both the sidebar and the inner page contents are scrollable.  Given that a combination of browser, OS, and OS settings (e.g., macOS) can result in the scrollbars rendering differently, we ideally want to find a solution that normalizes these and clearly communicates independent scrollable regions.

**Comment by spadgett** [comment]
@rhamilto Is this fixed by #102?

**Comment by rhamilto** [comment]
Almost.  The fixing of the search bar resulted in the masking of the top of the main content area scrollbar.  Will fix this morning.

![screen shot 2017-04-10 at 8 35 17 am](https://cloud.githubusercontent.com/assets/895728/24861969/af6936d2-1dc8-11e7-8216-048747db6525.PNG)
